- src/db/schema.sql
> fix: Correct a trivial typo in SQL schema docs.

- src/db/models.rs
- src/db/models_test.rs
- src/db/schema.sql
also addressed or at least added comments for all of rfk's comments from yesterday
> feat: more db code and tests

- src/handlers.rs
Relocate structs in use by handlers to the top. Removes macros from the
handlers.
Closes #24
> feat: remove macros from handlers

- src/db/mod.rs
- src/db/mysql/models.rs
- src/db/mysql/pool.rs
- src/db/mysql/test.rs
- src/db/params.rs
- src/db/results.rs
- src/web/auth.rs
- src/web/handlers.rs
prefer test fns returning Results (now that rust supports it) vs unwraps
switch the CollectionCache to an Arc for convenience
Issue #18
> feat: add post_bsos and get_collection_counts/sizes

- src/web/extractors.rs
> feat: add a precondition header validator/extractor

- src/web/auth.rs
- src/web/extractors.rs
- src/web/handlers.rs
> feat: add collection/bso extractors for get/delete requests

- src/db/error.rs
- src/db/mysql/diesel_ext.rs
- src/db/mysql/mod.rs
- src/db/mysql/models.rs
- src/db/mysql/test.rs
and basic tests to just ensure it works
Closes #52
> feat: add lock_for_read/write

- src/db/error.rs
- src/db/mock.rs
- src/db/mod.rs
- src/db/mysql/mod.rs
- src/db/mysql/models.rs
- src/db/mysql/pool.rs
- src/db/mysql/test.rs
- src/db/params.rs
- src/db/results.rs
- src/main.rs
- src/server/mod.rs
- src/server/test.rs
- src/web/extractors.rs
- src/web/handlers.rs
- src/web/middleware.rs
- get/post_collection -> get/post_bsos
- fix the ownership todo in post_bsos
- fix get_collection_modified's handling of empty sets
- add clone to Box<dyn Db> for sharing Dbs among handlers & req.extensions
w/out an Rc
- have the pool run migrations and fix an unwrap() in run_embedded_migrations
Closes #65
> feat: fully plugin the db into remaining handlers & server

- src/web/extractors.rs
- src/web/handlers.rs
> feat: refactor State extraction to Box db and add put/post BSO tests

- src/web/extractors.rs
- src/web/middleware.rs
> fix: don't finish transactions unless one was started

- migrations/2018-08-28-010336_init/up.sql
- src/db/results.rs
- src/db/util.rs
- src/server/test.rs
- src/web/handlers.rs
also:
- support get_collection_ids for get_collection !full
- serialize (and deserialize for tests) SyncTimestamp as 2 decimal digit
precision floats
> feat: plugin delete_bsos to the delete_collection handler

- .travis.yml
- src/db/mock.rs
- src/db/mod.rs
- src/db/mysql/batch.rs
- src/db/mysql/models.rs
- src/db/mysql/test.rs
- src/db/params.rs
- src/db/results.rs
- src/web/handlers.rs
and remove the 1.30.0 docs warning now that ci uses 1.30.1
> refactor: modified -> timestamp

- src/db/error.rs
- src/error.rs
- src/server/test.rs
- src/web/handlers.rs
and include an X-Weave-Records header
Closes #98
Issue #101
> fix: return empty on get of non existent collections

- src/error.rs
- src/web/error.rs
- src/web/extractors.rs
- src/web/handlers.rs
> feat: return newlines reply when get accept header indicates it

- src/server/mod.rs
- version.json
> feat add dockerflow endpoints

- CONTRIBUTING.md
- README.md
> docs: more on installation/running individual tests

- Cargo.lock
- Cargo.toml
- src/web/extractors.rs
> bug: Allow text/plain, application/json, or no content type to be accepted

- src/db/mysql/test.rs
- src/web/auth.rs
- src/web/extractors.rs
> bug: exclude empty-ish application/newline content.

- src/db/mysql/models.rs
> Use INSERT ON DUPLICATE KEY UPDATE in put_bso

- Cargo.lock
- Cargo.toml
- db-tests/Cargo.lock
- src/db/mod.rs
- src/db/mysql/diesel_ext.rs
- src/db/mysql/models.rs
- src/db/mysql/pool.rs
- src/db/spanner/models.rs
- src/db/spanner/pool.rs
- src/error.rs
- src/lib.rs
- src/server/test.rs
- src/web/extractors.rs
- src/web/middleware.rs
also enable warning rust_2018 idioms
Closes #166
> chore: remove the smallvec dep override

- src/server/test.rs
- src/settings.rs
- src/web/auth.rs
- src/web/extractors.rs
- src/web/middleware.rs
> Feat: remove unwraps from production path

- Cargo.lock
- Cargo.toml
- db-tests/Cargo.lock
- src/db/spanner/macros.rs
- src/db/spanner/mod.rs
- src/db/spanner/models.rs
- src/db/spanner/support.rs
- src/main.rs
And some additional attempts at compatibility with the new grpc client lib via the google_grpc build flag (currently untested/likely broken)
>  refactor: add params! and param_types! macros

- src/web/auth.rs
> bug: Add 1000 years for test cases to prevent premature Hawk expiration

- README.md
Mainly opening this to update the mysql connection string url with relevant details for username/password. Made a few other minor tweaks while I was in here.
> docs: update readme with a few more first time setup details

- src/server/mod.rs
- src/web/extractors.rs
- src/web/middleware.rs
> bug: do not require auth for dockerflow

- db-tests/src/db_tests.rs
- src/db/mock.rs
- src/db/mod.rs
- src/db/mysql/models.rs
- src/db/mysql/pool.rs
- src/db/results.rs
- src/db/spanner/batch.rs
- src/db/spanner/manager.rs
- src/db/spanner/models.rs
- src/db/spanner/pool.rs
- src/db/spanner/support.rs
- utilize Spanner's UNNEST (w/ ListValue params)
- add a basic test of the collection cache
- misc cleanup/additional comments
Closes #212
(there's a few pending XXX: comments in the spanner module w/ existing issues or w/ pending new issues I'll log shortly)
> fix: cleanup TODOs

- db-tests/Cargo.lock
- migrations/2018-08-28-010336_init/down.sql
- migrations/2019-09-11-164500/down.sql
- migrations/2019-09-11-164500/up.sql
- src/db/mysql/models.rs
- src/db/mysql/schema.rs
* for continuity, ensure that we use the original column names for mysql
* added non-destructive migration for existing tables.
Closes #194
> feat: make mysql use existing column names

- .circleci/config.yml
- db-tests/src/support.rs
- migrations/2018-08-28-010336_init/up.sql
- migrations/2019-09-25-174347_min_collection_id/down.sql
- migrations/2019-09-25-174347_min_collection_id/up.sql
- src/db/mod.rs
- src/db/mysql/test.rs
- src/db/spanner/batch.rs
- src/db/spanner/models.rs
- src/lib.rs
- src/web/middleware.rs
and fix reservation of the std collection id space w/:
- a small adjustment to spanner's autoincrement
- a dummy value on mysql (nothing else is preserved between mysqld restarts)
and enable docker hub deploying
Closes #223, #231
> fix: get the session timestamp from Spanner

- db-tests/src/db_tests.rs
- src/db/mysql/models.rs
- src/db/mysql/schema.rs
- src/db/spanner/models.rs
- src/web/middleware.rs
> feat: Set tombstone on deleted data for user.

- src/db/mysql/models.rs
- src/db/spanner/models.rs
following https://www.sqlstyle.guide/
(getting this all more readable/manageable now before upcoming schema changes)
> refactor: reformat the SQL (except batch)

- src/db/spanner/batch.rs
> bug: Fix spanner batches to use new fxa_uid as userid

- src/web/extractors.rs
> bug: Be more permissive about content type headers

- spanner-2019-10-01.ddl
- src/db/spanner/models.rs
- src/db/spanner/support.rs
leaving the old impl. behind a cfg toggle for the db_tests (for now)
Closes #267
> feat: rewrite post/put_bsos w/ spanner mutations

- Cargo.lock
- Cargo.toml
- Dockerfile
- spanner-2019-10-01.ddl
- src/main.rs
avoiding the reqwest transports issues with likely grpcio's boringssl
Closes #289
> fix: switch sentry to its curl transport

- db-tests/Cargo.lock
- src/web/extractors.rs
> bug: accept weighted content-type headers

- src/db/spanner/pool.rs
by (temporarily) increasing the connection timeout value
Closes #302
> feat: workaround timeouts w/ larger db conn sizes

- src/db/spanner/batch.rs
- src/db/spanner/macros.rs
- src/db/spanner/models.rs
- src/db/spanner/support.rs
> feat: removed SpannerType enum

- src/db/mysql/models.rs
- src/db/spanner/models.rs
* some cleanup to DRY the bso fetch code query builds on spanner.
* TODO: consider doing the same for MySQL.
Closes #248
> feat: get_bso_ids only loads the id column

- src/db/error.rs
- src/db/spanner/manager.rs
and move grpcio::Errors into their own DbErrorKind variant. we were mistakenly
using the `Connection` type, which is only for the rare error from diesel
Connection::establish
Closes #316
> fix: recreate stale spanner sessions on checkout

- Dockerfile
> chore: Update dockerfile to rust 1.39

- Cargo.lock
- db-tests/Cargo.lock
- src/main.rs
Also update the Cargo.lock files so that building on macOS works again.
> Fix #321 Specify the release name to sentry

- README.md
Just extend documentation; Nothing to test beyond.
> README.md: Add missing requirements

- spanner-2019-10-01.ddl
> fix: oops, properly interleave this index

- src/server/test.rs
- src/web/extractors.rs
(followup to 013eaafd)
bsos_can_have_a_collection_field
Closes #376
> fix: ignore the collection field in POSTS also

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> chore: tag 0.1.11

- src/server/metrics.rs
- src/settings.rs
- src/web/extractors.rs
- src/web/middleware/db.rs
- src/web/middleware/precondition.rs
Closes #416
* error: requires action or attention
* warn: non-critical event impacting performance or function
* info: notification of interest
* debug: crap
no code impact (aside from logging)
Closes #416.
> feat: recategorize logging messages into appropriate states

- db-tests/src/db_tests.rs
- db-tests/src/support.rs
- src/db/mod.rs
- src/db/mysql/models.rs
- src/db/results.rs
- src/db/spanner/models.rs
- src/db/spanner/support.rs
- src/web/extractors.rs
- src/web/handlers.rs
The python code had an optimization which the rust code did not. Ported this optimization to rust.
The `cargo test`s and db-tests pass now, but I'm still not completely sure how to test the new functionality.
?
Fix #53
> perf: Port get_bsos' pagination optimization

- db-tests/Cargo.lock
- src/db/spanner/batch.rs
- src/db/spanner/models.rs
- src/db/spanner/support.rs
- src/web/extractors.rs
and simplify get_bso_ids' processing
also revert the temp. sentry tags for the mutation limit issue
db/integration tests
Closes #422, #389
> refactor: kill unnecessary copies from protobuf Values

- Cargo.lock
- Cargo.toml
- db-tests/Cargo.lock
- db-tests/src/batch.rs
- db-tests/src/db_tests.rs
- db-tests/src/support.rs
- src/db/mock.rs
- src/db/mod.rs
- src/db/mysql/models.rs
- src/db/mysql/pool.rs
- src/db/spanner/models.rs
- src/db/spanner/pool.rs
- src/db/spanner/support.rs
- src/error.rs
- src/main.rs
- src/server/metrics.rs
- src/server/mod.rs
- src/server/test.rs
- src/web/auth.rs
- src/web/extractors.rs
- src/web/handlers.rs
- src/web/middleware/db.rs
- src/web/middleware/precondition.rs
- src/web/middleware/sentry.rs
- src/web/middleware/weave.rs
- src/web/tags.rs
This pr updates to actix web 2 and future 0.3, but does not switch anything to async await.
Assuming it compiles, cargo test, cargo test in db-tests, and the python tests all pass, it should be good to go.
Closes #394
> Upgrade to actix web 2

- src/web/extractors.rs
Fix the nits from @pjenvey 's review of the actix-2 branch.
Closes #443.
> Fix #443 Fix the nits from @pjenvey 's review of the actix-2 branch.

- src/db/spanner/models.rs
Convert straggler functions to async await
- get_storage_usage
- delete_storage
- check
Closes #453.
> refactor: Fix #453 Convert straggler functions to async await

- src/db/spanner/models.rs
There was one remaining blocking execute left over from the db async/await conversion work. Change it to execute_async.
Closes #457.
> fix: Fix #457 remaining blocking execute

- README.md
and update the ToC
Rendered: https://github.com/mozilla-services/syncstorage-rs/tree/chore/link-to-matrix#syncstorage-rs
Issue https://github.com/mozilla-services/services-engineering/issues/35
> chore: add a badge for matrix

- README.md
Not sure why this patch was stalled by CI, trying an insertion.
Provided by @undef1nd via #472
documentation, no test required
N/A
> doc: Applying patch from @undef1nd #472

- README.md
Add system dependencies to README
Closes #255.
> doc: add system dependencies to README

- tools/user_migration/migrate_node.py
since bsos INTERLEAVE's w/ DELETE CASCADE
- persist unique_key_filter across writes
- fix new bundling of of bso_values for inserting bsos
- add TODO for fixing user_collections' modified time
> fix: don't replace user_collections

- tools/user_migration/migrate_node.py
deletes pre-existing user data on spanner before migrating. only usable
in --user mode.
and fix parsing of the new gen_fxa_users.py output
For users w/ existing data in Spanner, migrate_node.py will emit a log message, e.g.:
`
DEBUG:root:Wiping user, collections: [(1, 'clients'), (2, 'crypto'), (3, 'forms'), (4, 'history'), (6, 'meta'), (7, 'bookmarks'), (8, 'prefs'), (9, 'tabs'), (11, 'addons')]
`
instead of skipping the user
Closes #596
> feat: add a --wipe_user mode

- Cargo.lock
- src/db/error.rs
- src/db/mock.rs
- src/db/mod.rs
- src/db/mysql/batch.rs
- src/db/mysql/models.rs
- src/db/mysql/pool.rs
- src/db/mysql/test.rs
- src/db/results.rs
- src/db/spanner/pool.rs
- src/db/tests/support.rs
- src/logging.rs
- src/server/mod.rs
- src/server/test.rs
- src/web/auth.rs
- src/web/error.rs
- src/web/extractors.rs
Against the release/0.3 branch. Also includes the additional pool metrics.
See #612 and #605 for the metrics
Issue #612
> chore: bump actix-rt for the memory leak

- src/web/handlers.rs
Squash and rebase of this: https://github.com/mozilla-services/syncstorage-rs/pull/594
Fix #543
> refactor: Convert actix-web frontend *_bso calls to async await

- src/db/spanner/models.rs
> refactor: quiet clippy warnings

- src/server/test.rs
- src/web/middleware/rejectua.rs
Against the release/0.4 branch
Unit test additions
Closes #683
> fix: don't reject firefox-ios dev builds

- src/db/spanner/batch_index.sql
Closes #719
This index should replace the existing BatchesExpry index.
N/A
Closes #719.
> bug: Replace batch index to resolve hot table problem

- tools/spanner/purge_ttl.py
Added `--uid_starts` option which will limit purge_ttl bso deletes to
fxa_uids that begin with specified characters.
(e.g.
`purge_ttl.py --uid_starts="AA" --collection_ids=[7,8]`
will limit to scanning bso tables to fxa_uid values that begin with "AA"
and only the 7 & 8 collections
Closes #713
> feat: option to limit purgettl to range of fxa_uids

- src/db/spanner/manager.rs
note google_default_credentials blocking concerns (#732)
Further stage load testing
Closes #731
Issue #732
> fix: switch create_session to async

- Dockerfile
> chore: Update Docker rust to 1.45

- src/db/transaction.rs
- src/web/handlers.rs
Further load testing on stage
Closes #736
> fix: avoid unneeded clones

- src/web/extractors.rs
Issue #757
Follow up for Issue #746 to allow `debug_client` for batch operations.
Issue #757
> add debug_client check to BsoBodies for batch operations.

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Tagging 0.5.5 release.
Clog look ok?
> chore: tag 0.5.5 release

- src/server/mod.rs
- src/server/test.rs
- src/web/extractors.rs
- src/web/handlers.rs
New unit test passes
Closes #759
> fix: ensure an X-Last-Modified for /info/configuration

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/web/middleware/rejectua.rs
All tests pass + load testing looks good
Closes #832
> feat: update to actix-web 3

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
* update to actix-web 3 (#834)
* added more detailed release process to README.md
* return correct error code and value for OverQuota users (#837)
> chore: Release/0.6.1

- src/db/spanner/batch.rs
- src/db/tests/batch.rs
dynamically build up params for each do_append update
> f ensure a pre-existing bso

- Cargo.toml
- src/db/mock.rs
- src/db/mod.rs
- src/db/mysql/models.rs
- src/db/spanner/batch.rs
- src/db/spanner/models.rs
- src/db/spanner/pool.rs
- src/db/tests/db.rs
> feat: switch coll cache's RwLock to async

- Cargo.lock
- Cargo.toml
- src/db/spanner/models.rs
- src/server/metrics.rs
- src/server/mod.rs
- src/web/tokenserver.rs
Closes: #928
Use more permissive CORS settings.
Using the `tools/example` scripts, try submitting a request with a blank or invalid ORIGIN header. 
Closes #928.
> bug: make actix-cors more permissive

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- vendor/mozilla-rust-sdk/googleapis-raw/src/lib.rs
Tagging 0.8.3 for release and also fixing minor issue with release docs.
Docs make sense?
N/A
> chore: tag 0.8.3

- src/web/extractors.rs
This was a potentially expensive clone of the entire bso's JSON Value
Closes #971
> feat: avoid an unnecessarily cloning for from_raw_bso

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Tagging 0.8.4 for release.
clog look ok?
N/A
> chore: tag 0.8.4

- src/server/metrics.rs
From @56quarters in #981
Delegate to count method and use glob import for metric traits
(resubmitting due to github commit signature issues -- jrc)
code refactor, no operational changes made or expected.
> refactor: remove duplicate code for incrementing counters (signed, see #981)

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
TODO: need to log an issue for ops for setting values for max lifetime/idle on stage
> chore: tag 0.9.1

- .circleci/config.yml
- tools/integration_tests/run.py
- tools/integration_tests/test_storage.py
- tools/integration_tests/test_support.py
Enable flake8 in circleci config for tools/integration_tests
Format contents in tool/integration_tests to be flake8 compliant
N/A
Closes #944
> chore: enable flake8 in circleci config for tools/integration_tests

- Cargo.lock
- Cargo.toml
- src/db/error.rs
- src/db/spanner/pool.rs
- src/error.rs
- src/web/error.rs
- src/web/middleware/sentry.rs
switch failure crate with thiserror and code changes that were required
Closes #1017.
> chore: switch failure crate with thiserror

- src/db/spanner/manager/bb8.rs
Remove Generic from SpannerSessionManager
Closes #697.
> remove generic from SpannerSessionManager

- README.md
- config/local.example.toml
- src/tokenserver/README.md
Adds a README to Tokenserver
N/A
Closes #1082
> docs: add Tokenserver README

- Dockerfile
- src/db/mysql/batch.rs
- src/web/tags.rs
Updates for the new rust version
No changes to functionality
N/A
> chore: update 12/2/21

- src/server/mod.rs
- src/settings.rs
route GET "/" to docs
Closes #1097 .
> route get / requests to sync docs

- Cargo.lock
- Cargo.toml
- config/local.example.toml
- src/server/mod.rs
- src/server/test.rs
- src/settings.rs
- src/web/mod.rs
- tools/integration_tests/run.py
- tools/integration_tests/test_storage.py
changes to allow cors allowed origin and max age to be configurable
Closes #930
> changes to allow cors allowed origin and max age to be configurable

- Cargo.lock
- Makefile
> chore: add Python build to Makefile

- src/db/spanner/batch.rs
- src/db/spanner/macros.rs
- src/db/spanner/models.rs
- src/db/spanner/schema.ddl
- src/db/spanner/support.rs
to avoid cloning, particularly of the payload
Closes #1300
(@ethowitz sorry for more #1281 conflicts but I wanted to get this into a 0.11.1 release)
> chore: to_spanner_value -> into_spanner_value

- Dockerfile
This file needs to be in the Docker image to be run
> chore: add process_account_events.py to Docker image

- .circleci/config.yml
- Dockerfile
> fix: write to the new version.json location

- CHANGELOG.md
- Cargo.lock
- syncstorage-common/Cargo.toml
- syncstorage-db-common/Cargo.toml
- syncstorage/Cargo.toml
- tokenserver-common/Cargo.toml
My first time tagging a new release; could use an extra close set of eyes on this one 😇
> chore: tag 0.12.0

- syncstorage/src/tokenserver/extractors.rs
Adds a `token_type` tag to the `syncstorage.tokenserver.token_verification` metric whose value can be either `BrowserID` or `OAuth`.
Closes #1358
> feat: tag Tokenserver's `token_verification` metric with the token type

- .circleci/config.yml
- syncserver-settings/src/lib.rs
- syncserver/src/server/mod.rs
- tools/integration_tests/run.py
- tools/integration_tests/test_storage.py
I must have made a mistake during a rebase -- https://github.com/mozilla-services/syncstorage-rs/commit/221705b7ea74c6dddffd1c5289c53b3ad2cc7522 wasn't properly applied to the settings crate reorg branch, and we weren't allowing all origins. This PR should resolve it
> bug: fix CORS issue

- Dockerfile
- tools/tokenserver/requirements.txt
and add PyBrowserID for it and tokenlib for purge_old_records.py
SRE will run it on next release
SVCSE-474
Issue #1086
> chore: add missing util.py to docker for process_account_events.py

- Dockerfile
(just add the whole dir this time)
This is against 0.13.2 (the release/0.13 branch).
SVCSE-474
Issue #1086
> chore: add another missing file to docker for process_account_events.py

- tools/tokenserver/database.py
- tools/tokenserver/test_process_account_events.py
a regression from the Python 3 conversion (max's changes)
(against release/0.13)
SVCSE-3633
> fix: handle nullable (None) keys_changed_at values

- Cargo.lock
- tools/tokenserver/process_account_events.py
- tools/tokenserver/test_process_account_events.py
[SYNC-3638](https://mozilla-hub.atlassian.net/browse/SYNC-3638)
(against release/0.13)
[SYNC-3638]: https://mozilla-hub.atlassian.net/browse/SYNC-3638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: connect to the db once instead of every loop iteration

- Makefile
- README.md
A couple of steps/changes I had to do to build syncstorage successfully!
The bits in the `Makefile` happy to omit, but i had to add those because I run python3.10 and the path referenced python 3.9
> Minor improvements to onboarding docs

- syncserver-settings/src/lib.rs
- syncstorage-db-common/src/lib.rs
- syncstorage-db/src/tests/db.rs
- syncstorage-db/src/tests/support.rs
- syncstorage-mysql/src/models.rs
- syncstorage-settings/src/lib.rs
- syncstorage-spanner/src/manager/deadpool.rs
- syncstorage-spanner/src/models.rs
- syncstorage-spanner/src/pool.rs
switch mutation usage to an explicit flag
fix the db tests' uid handling
Closes SYNC-3955
> fix: switch more test flags to cfg(debug_assertions)

- README.md
- docker-compose.spanner.yaml
> chore: missed fixes from rollup

- syncstorage-mysql/src/error.rs
- syncstorage-spanner/src/error.rs
> fix: restore emitting backend specific db errors to sentry

- tools/integration_tests/tokenserver/test_e2e.py
- tools/tokenserver/database.py
- tools/tokenserver/purge_old_records.py
- tools/tokenserver/test_database.py
In an attempt to parallelize this script after a very long delay, specify a range so that multiple scripts can try to process different ranges of the database.
Issue  SYNC-4246.
> feat: Allow uid range for purge function (SYNC-4246)

- tools/tokenserver/database.py
Closes [SYNC-4264](https://mozilla-hub.atlassian.net/browse/SYNC-4264)
[SYNC-4264]: https://mozilla-hub.atlassian.net/browse/SYNC-4264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Ignore non-spanner nodes for scripts

- requirements.txt
- tools/integration_tests/requirements.txt
- tools/tokenserver/requirements.txt
> chore: bump crytography/pyramid to quiet a number of security alerts

- syncstorage-spanner/src/batch.rs
- syncstorage-spanner/src/models.rs
> docs: clarify the handling of existing expired bsos in writes

- syncserver/src/tokenserver/mod.rs
> fix: don't hide TokenserverPool initialization errors on startup

- Dockerfile
this also downgrades Oracle's libmysqlclient-dev from 8.0.37-1debian11 to 8.0.39-1debian12
this is to test if the debian version and or the libmysqlclient-dev version are the cause of both db pool initialization failures as well as other seemingly mysterious likely network related issues seen in 0.17.x
stage/prod testing
Issue SYNC-4363
> chore: revert back to bullseye (for now)

- .cargo/audit.toml
- tools/tokenserver/process_account_events.py
so the script can operate under bullseye/python3.9
Issue SYNC-4259
> fix: revert the python3.10 match statement (for now)

- syncstorage-spanner/src/manager/session.rs
- tools/tokenserver/util.py
and remove syncstorage dbg! statements
Issue SYNC-4259
> feat: pickup the syncserver metrics settings

- tools/tokenserver/process_account_events.py
- tools/tokenserver/purge_old_records.py
- tools/tokenserver/util.py
> fix: correctly read the SYNC_STATSD_HOST/PORT settings

- syncserver-db-common/src/error.rs
> feat: namespace the db error labels

- docs/tools/purge_old_records_tokenserver.md
> docs: update purge script's status now that it's running

- Dockerfile
- requirements.txt
- tools/integration_tests/requirements.txt
bump cryptography and remove apparently no longer needed build flags
> chore: update python cryptography

- syncserver-common/src/lib.rs
- syncserver-common/src/middleware/sentry.rs
- syncserver-db-common/src/error.rs
- syncserver/src/error.rs
- syncserver/src/web/auth.rs
- syncserver/src/web/error.rs
- syncserver/src/web/extractors.rs
- syncserver/src/web/mod.rs
- syncstorage-db-common/src/error.rs
- syncstorage-mysql/src/error.rs
- syncstorage-spanner/src/error.rs
- tokenserver-common/src/error.rs
- tokenserver-common/src/lib.rs
- tokenserver-db/src/error.rs
and kill tokenserver's TokenType now that it's solely oauth
Issue STOR-64
> refactor: simplify metric_label to return a &str

- syncserver-common/src/middleware/sentry.rs
- syncserver/src/tokenserver/extractors.rs
- tokenserver-auth/src/oauth/py.rs
- tokenserver-common/src/error.rs
and fix the sentry middleware to use ReportableError::tags
Closes STOR-201
> feat: emit oauth verification timeouts as metrics (not sentry)

- .circleci/config.yml
- Cargo.toml
- Dockerfile
- requirements.txt
- syncserver-common/src/lib.rs
- syncserver/src/tokenserver/extractors.rs
- syncserver/src/tokenserver/mod.rs
- syncserver/src/web/extractors.rs
- syncserver/src/web/handlers.rs
- syncserver/src/web/middleware/rejectua.rs
- syncstorage-db-common/src/lib.rs
- syncstorage-mysql/src/lib.rs
- syncstorage-spanner/src/models.rs
- syncstorage-spanner/src/pool.rs
- tokenserver-db/src/lib.rs
- tools/integration_tests/requirements.txt
- tools/integration_tests/tokenserver/test_e2e.py
w/ the pyfxa 0.8.1 fix
Closes STOR-204
> fix: re-enable tokensever e2e tests

- syncstorage-spanner/src/error.rs
- syncstorage-spanner/src/lib.rs
- syncstorage-spanner/src/stream.rs
- syncstorage-spanner/src/support.rs
adds a test for STOR-212 (you can see the change outside of the refactor in the second commit)
Issue STOR-212
> test: make StreamedResultSet's stream generic

- syncstorage-spanner/src/error.rs
Ongoing cleanup of sentry events (e.g. hiding “expected Errors” that we initially sent to Sentry to sanity check as we rolled out the new service). (Issue [#923](https://github.com/mozilla-services/syncstorage-rs/issues/923), [#872](https://github.com/mozilla-services/syncstorage-rs/issues/872) likely related).
Also let’s ensure we’re only sending 5xx status errors to sentry (per the old bug 
) – this seems to already be the case but looking at SyncstorageDbError::is_sentry_event suggests the not found variants of that error would be reported to sentry (but are 404s). Also  notes some 4xxs generated by the e2e test were going to sentry.
Closes [STOR-151](https://mozilla-hub.atlassian.net/browse/STOR-151).
[STOR-151]: https://mozilla-hub.atlassian.net/browse/STOR-151?atlOrigin=eyJpIjoiNWRkN …
> refactor: sync sentry cleanup grpc errors

- .circleci/config.yml
- README.md
- docker-compose.mysql.yaml
- docker-compose.spanner.yaml
- syncstorage-mysql/src/diesel_ext.rs
- syncstorage-mysql/src/models.rs
BREAKING CHANGE: now depending on >= mysql 8 features
Closes STOR-160
> chore: require minimum mysql 8

- syncstorage-db-common/src/lib.rs
The default implementation of Db::extract_resource doesn’t use async/await. The core of this method should be converted to an {{async {}}} block so it can utilize async/await for better readability (as we’ve already done for e.g. [many of the extractors](https://github.com/mozilla-services/syncstorage-rs/issues/544)).
Closes [STOR-101](https://mozilla-hub.atlassian.net/browse/STOR-101).
[STOR-101]: https://mozilla-hub.atlassian.net/browse/STOR-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: convert db extract calls to async

- .circleci/config.yml
- Dockerfile
- Makefile
- docker-compose.e2e.mysql.yaml
- docker-compose.e2e.spanner.yaml
- tools/integration_tests/test_storage.py
- tools/integration_tests/test_support.py
- tools/integration_tests/tokenserver/test_authorization.py
- tools/integration_tests/tokenserver/test_e2e.py
- tools/integration_tests/tokenserver/test_misc.py
- tools/integration_tests/tokenserver/test_node_assignment.py
- tools/spanner/count_expired_rows.py
- tools/spanner/purge_ttl.py
- tools/spanner/test_count_expired_rows.py
- tools/spanner/test_purge_ttl.py
- tools/spanner/test_utils.py
- tools/spanner/utils.py
- tools/spanner/write_batch.py
With tests and utilities living in a nested directory, they required altering the PYTHONPATH in certain situations (like when invoked by py.test). We should be able to move them to Python imports to avoid altering the path.
In the case of a Docker environment, and that mixing relative and absolute paths is an antipattern, the solution is as follows:
- An addition of `__init__.py` files to each package directory to build from the `tools/` directory. This allows proper package and module resolution
- Update of all imports to be absolute, increasing reliability and clarity.
- Any mocks or case of calls are also adjusted for explict imports
- the Docker e2e tests include addition of `PYTHONPATH=app/` so that the tests are invoked from the root of the sync app, which is `app/`. We should be in …
> refactor : python imports

- syncstorage-spanner/src/error.rs
- syncstorage-spanner/src/pool.rs
> feat: quiet pool timeout events (emit as metrics)

- syncstorage-spanner/src/error.rs
and quiet some INTERNAL grpc errors
Closes STOR-313
> feat: emit sentry events for INVALID_ARGUMENT

- syncserver/src/web/handlers.rs
- syncserver/src/web/transaction.rs
- syncstorage-db-common/src/lib.rs
- syncstorage-db/src/mock.rs
- syncstorage-mysql/src/models.rs
- syncstorage-spanner/src/models.rs
by utilizing async closures' improved borrowing semantics
Closes STOR-350
> feat: kill Db's impl of Clone

- Cargo.lock
- Cargo.toml
- tokenserver-db-common/Cargo.toml
- tokenserver-db-common/src/error.rs
- tokenserver-db-common/src/lib.rs
- tokenserver-db-common/src/params.rs
- tokenserver-db-common/src/results.rs
- tokenserver-db/Cargo.toml
- tokenserver-db/src/lib.rs
- tokenserver-db/src/mock.rs
- tokenserver-db/src/models.rs
- tokenserver-db/src/pool.rs
> refactor: move shared tokenserver db into tokenserver-db-common

- Cargo.lock
- syncserver-db-common/Cargo.toml
- syncserver-db-common/src/error.rs
- syncserver-db-common/src/lib.rs
- syncserver-db-common/src/test.rs
- syncserver/src/server/mod.rs
- syncserver/src/server/test.rs
- syncserver/src/tokenserver/mod.rs
- syncstorage-db-common/Cargo.toml
- syncstorage-db-common/src/lib.rs
- syncstorage-db/src/tests/support.rs
- syncstorage-mysql/Cargo.toml
- syncstorage-mysql/src/batch.rs
- syncstorage-mysql/src/error.rs
- syncstorage-mysql/src/models.rs
- syncstorage-mysql/src/pool.rs
- syncstorage-mysql/src/test.rs
- syncstorage-settings/src/lib.rs
- tokenserver-db-common/Cargo.toml
- tokenserver-db-common/src/error.rs
- tokenserver-db-postgres/Cargo.toml
- tokenserver-db-postgres/src/pool.rs
- tokenserver-db/Cargo.toml
- tokenserver-db/src/pool.rs
Closes [STOR-364](https://mozilla-hub.atlassian.net/browse/STOR-364)
[STOR-364]: https://mozilla-hub.atlassian.net/browse/STOR-364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: switch syncstorage to diesel-async
