- src/db/models.rs
- src/dispatcher.rs
- src/handlers.rs
- src/server.rs
- src/server/mod.rs
- src/server/test.rs
I spent a bit of time today working on dispatchers for `get_bso` and `put_bso`. Although they broadly seem to work (they compile! :smile:), I'm not very happy with the code as it stands. As usual I had some trouble bending Rust to my will, hence I'm opening a WIP PR in the hope that you guys can help me with some async pointers on what I could be doing better.
The main problem I struggled with was extracting the common code from the two dispatcher bodies out to a separate method. As you'll see in the diff, there is a fair amount of duplicate code in each body and the indentation got pretty crazy as it wouldn't let me flatten the combinator chains.
I tried two things to fix it:
1. A helper method on `DBExecutor` that returns `MutexGuard<DBManager>`:
```rust
impl DBExecutor {
fn lock(&self, …
```
> feat: handlers and dispatchers for get_bso and put_bso

- .travis.yml
- src/dispatcher.rs
- src/handlers.rs
- src/server/mod.rs
Not sure how you guys feel about this, no worries if it's not wanted for some reason.
Anyway, it was kind of low-level annoying last week when I ran `cargo fmt` and a bunch of files unrelated to my changes were also updated. If we run it in CI it makes it easier to stay on top of things is all I'm thinking.
There is a slight hack in the CI script because `--write-mode=diff` doesn't exit with an error code when there are diffs, so I added an explicit exit to make it fail. That's just a temporary measure until we can use `--check` in stable.
Just to prove that it actually fails when there are diffs, you can see the failing build for 58f5481 here:
https://travis-ci.org/philbooth/syncstorage-rs/builds/410320506
And here is the follow-up build for 80e4471 with the fixes: …
> fix: turn on cargo fmt in CI and fix fmt errors

- Cargo.lock
- Cargo.toml
- src/db/models.rs
- src/main.rs
- src/server/test.rs
When I wrote the server tests I hadn't understood what `SyncArbiter::start` does, so didn't realise the callback was being invoked on every request. This change moves construction of the db stuff out of that callback, so the same `DBManager` gets used for the entire life of the `TestServer` instance.
As a result of that, I could also write the test that I couldn't get to work last week in #4: a round-trip of `put_bso` then `get_bso`, followed by some assertions that what comes out is the same as what went in. Hence those assertions are also added to the `put_bso` test.
@pjenvey, @bbangert r?
> fix(tests): stop creating a fresh DBManager on every request

- .travis.yml
- src/db/models.rs
- src/db/models_test.rs
- src/dispatcher.rs
- src/handlers.rs
- src/server/mod.rs
- src/server/test.rs
This afternoon I started stubbing out some more of the API endpoints, the `info/...` ones and `delete_bso`. Handlers and dispatchers are added, but obviously there's no attempt to wire anything into the db layer here.
While doing that, all of the boilerplate started to get a bit annoying so I tried to eliminate some of it using macros. Not sure how intuitive the macro format I ended up with is, so I'm interested to see whether you guys have suggestions to improve those.
I also had to update the `cargo fmt` invocation in travis because of the 1.28.0 release (as predicted by Phil J in #6). That change is included here too along with some related `rustfmt` fixes to `db/models.rs` and `db/models_test.rs`, just so that the build would succeed in Travis.
@bbangert @pjenvey r?
> feat: stub out some more endpoints

- src/dispatcher.rs
- src/handlers.rs
- src/main.rs
- src/server/mod.rs
- src/server/test.rs
The substantive change here is just to add the remaining handler stubs for the collection endpoints. That should mean all the endpoints listed in the API docs now have a handler, unless I've missed any.
Note that `DELETE /storage/{collection}` has two entries in the docs but only one handler here. It behaves differently depending on whether there is an `ids` query param (or rather, it *will* behave differently when we actually hook it up to some behaviour). But obviously that's all just one resource in actix-web's view of things.
In addition to that there's some other small fixes:
* A rustfmt fix for some `extern crate` ordering.
* Some of the repetition between similar macro rules has been eliminated by moving it to a common base macro. This took me longer to get right than I anticipated …
> feat: add handler stubs for collection endpoints

- src/data.rs
- src/handlers.rs
- src/server/mod.rs
- src/server/test.rs
Fixes #13.
I thought I'd covered all the outstanding endpoints in #9, but I didn't spot `DELETE /{uid}` and `DELETE /{uid}/storage`. Those are definitely the last two though, unless there are others not in the document I'm referring to:
https://mozilla-services.readthedocs.io/en/latest/storage/apis-1.5.html
@bbangert @pjenvey r?
> feat: add handler stub for DELETE /{uid}

- src/db/mock.rs
- src/db/mod.rs
- src/db/params.rs
- src/db/results.rs
- src/handlers.rs
- src/main.rs
- src/server/mod.rs
- src/server/test.rs
Fixes #16.
Continuing from the conversation about my WIP branch in IRC yesterday, this leaves the existing db code mostly untouched but defines a new `Db` trait, plus a `MockDb` stubbed implementation thereof.
I say "mostly" untouched because the old `src/db/mod.rs` has been completely clobbered, so that old code is not actually being compiled any more. I realise that's not very different from deleting it all, but there were enough points of difference here in both the struct definitions and where I've moved them to that it really seemed cleaner to start anew. I'll call out some of those differences in the inline comments and hopefully they make sense to you guys. If not, I can revert some stuff, no worries.
I hooked the new trait into a mock implementation just so the tests would have …
> feat: define and mock a db trait

- .travis.yml
- Cargo.lock
- Cargo.toml
- migrations/2018-08-28-010336_init/down.sql
- migrations/2018-08-28-010336_init/up.sql
- src/db/error.rs
- src/db/mock.rs
- src/db/mod.rs
- src/db/mysql/mod.rs
- src/db/mysql/models.rs
- src/db/mysql/schema.rs
- src/db/mysql/test.rs
- src/db/params.rs
- src/db/results.rs
- src/db/util.rs
- src/handlers.rs
- src/main.rs
- src/server/mod.rs
- src/server/test.rs
- src/settings.rs
w/ some initial calls and a test suite migrated from the sqlite version
- prefers raw DQL (note: not DML) queries vs diesel's query builder for
potential reuse for other backends (spanner)
- TODO: further fleshing out of the types, likely wanting i64 or wrappers
everywhere (as all spanner has is INT64) -- nor should the db layer be
responsible for conversions from unsigned
Issue #18
> feat: beginnings of a mysql backend

- src/auth/mod.rs
- src/auth/test.rs
- src/db/mysql/test.rs
- src/server/mod.rs
- src/server/test.rs
- src/settings.rs
Fixes #26.
The `master_secret` setting is a `Vec<u8>`, for which there is no default deserialization. This change pulls it out to a struct and implements `Deserialize` so that it can be set with a string via environment variable or config file.
That change also represented an opportunity to cache the value of `signing_secret`, which was being freshly calculated on every request even though the value is a constant derived from `master_secret`. So the struct is actually called `Secrets` and has two properties.
This does leave a slightly weird naming mismatch that I wasn't sure what to do with. `master_secret` makes sense from the perspective of setting e.g. a `SYNC_MASTER_SECRET` environment variable, but it looks kind of funny when the code accesses that property internally as a `Secrets` …
> feat: implement Deserialize for the master_secret setting

- src/db/models_test.rs
- src/db/mysql/models.rs
- src/db/mysql/schema.rs
- src/db/results.rs
temporary until (likely) diesel 1.4:
https://github.com/diesel-rs/diesel/issues/1785
> chore: quiet diesel warnings under rust 1.29

- src/db/error.rs
- src/db/mod.rs
- src/db/mysql/mod.rs
- src/db/mysql/models.rs
- src/db/mysql/pool.rs
- src/db/mysql/test.rs
- src/server/mod.rs
- src/server/test.rs
and a couple more db calls that utilize it
Issue #18
> feat: add collection id/name caching at the pool level

- src/main.rs
- src/server/mod.rs
- src/web/middleware.rs
- src/web/mod.rs
Only the timestamp middleware seems relevant, as the other two in
Python are for handling Python web framework implementation details.
The Rust version will likely require different approaches.
Closes #31
> feat: port python sync tween for weave timestamp

- src/db/mysql/models.rs
- src/db/mysql/test.rs
- src/db/params.rs
- src/web/auth.rs
- src/web/extractors.rs
- src/web/handlers.rs
Per extract_target_resource extraction from the Python version, this
add's uid validation to the HawkIdentifier extraction.
Issue #48
> feat: add path uid validation to HawkIdentifier extractor

- scripts/build-docs.sh
Sorry, I only tested my changes to this script locally before pushing them and accidentally included a bash-style `&&` operator that [fails in travis](https://travis-ci.org/mozilla-services/syncstorage-rs/builds/441775963#L548-L551):
```
$ ./scripts/build-docs.sh
Branch: master    Pull request: false
./scripts/build-docs.sh: 11: [: master: unexpected operator
Not building docs for deployment, omitting dependencies.
```
@r?
> fix: use posix-friendly logical and in docs script

- scripts/build-docs.sh
I actually checked the [build output](https://travis-ci.org/mozilla-services/syncstorage-rs/builds/442286722#L546-L550) this time and it appears to have run without errors:
```
$ ./scripts/build-docs.sh
Branch: pb/fix-docs-script-again    Pull request: false
Not building docs for deployment, omitting dependencies.
Documenting syncstorage v0.1.0 (file:///home/travis/build/mozilla-services/syncstorage-rs)
Finished dev [unoptimized + debuginfo] target(s) in 17.94s
```
Thanks for the tip @pjenvey, you were right about the single/double equals.
r?
> fix: use single = for equality test in docs script

- src/db/error.rs
- src/error.rs
- src/main.rs
- src/web/auth.rs
- src/web/error.rs
- src/web/handlers.rs
- src/web/mod.rs
Opened as a first step to fixing #38, only affecting the db and hawk stuff for now. I started to map the validation errors too but there's a lot of code there and it'll probably take me a few attempts to get right, so this seemed worth reviewing in the meantime.
As per #67, there is a top-level `ApiError` that `DbError` and `HawkError` get mapped to. Having one top-level error means we only have to `impl ResponseError` on one thing.
I moved `ApiError` up to `src/error.rs` because it contains a couple of macros that are used in both `src/db/error.rs` and `src/web/error.rs`, so I figured it made sense. And yeah, I got busy with the macros again. 😱
I'm happy to remove them if they're not welcome, I just thought they tidied up some boring and repetitive type-related hoops that we have to jump …
> feat: map db and hawk errors to a common top-level error type

- src/db/error.rs
- src/error.rs
- src/web/error.rs
- src/web/extractors.rs
~~Note this branch is based off the branch for #69, so if you want to review both commits in this PR that's cool, or if it's easier to review them separately I can wait until that one is merged and then rebase this against `master`.~~ (rebased now)
Anyway, this is another step on the road to fixing #38. (I guess just the middleware is left after this?)
It updates the validation errors in `src/web/extractors.rs` to map to `ApiError`. In addition to mapping the error types, it also meant bringing across the status code and serialization stuff, hence `ApiError` has grown a `status` property and there are some implementations of `Serialize` introduced to make sure we return all the error details.
Additionally, because a couple of the db errors seemed like 400s rather than 500s, `DbError` has …
> refactor: convert validation errors to use failure

- Cargo.lock
- Cargo.toml
- src/db/mock.rs
- src/db/mod.rs
- src/db/mysql/models.rs
- src/db/mysql/pool.rs
- src/db/mysql/test.rs
- src/db/params.rs
- src/db/results.rs
- src/main.rs
- src/server/mod.rs
- src/server/test.rs
- src/web/auth.rs
- src/web/extractors.rs
- src/web/handlers.rs
- src/web/middleware.rs
adds a transaction/collection lock middleware + a Db extractor
tokio_threadpool::blocking won't work under actix, so:
- manage our own ThreadPool, satisfying our async interface via cloning the
MysqlDb before sending it over to the ThreadPool
- unfortunately requires wrapping the inner state in Arc (and RefCell for the
mutable parts) and an accompanying unsafe Send and
Issue #65
> feat: initial integration of db w/ handlers

- .travis.yml
- src/db/mock.rs
- src/db/mod.rs
- src/db/mysql/models.rs
- src/db/mysql/test.rs
- src/db/params.rs
- src/db/results.rs
- src/server/test.rs
- src/web/handlers.rs
- kills get_collection_id (only used within the db layer now)
- simplify uid_data! (just alias HawkIdentifier)
- phrasing
Issue #65
> feat: plugin and cleanup various trait methods into MysqlDb:

- src/error.rs
- src/web/middleware.rs
Fixes #38 (I think?)
I was not feeling inspired when naming the new error type so ended up having a minor collision with actix's `ResponseError` trait. If one of you has a better name suggestion that avoids the need to alias that, let me know.
@bbangert @pjenvey r?
> refactor: map to failure errors in X-Weave-Timestamp middleware

- Cargo.lock
- src/db/params.rs
- src/server/test.rs
- src/web/error.rs
- src/web/extractors.rs
- src/web/handlers.rs
> feat: add put bso and post collection validator/extractors

- src/db/error.rs
- src/db/mysql/models.rs
- src/db/mysql/test.rs
- src/db/results.rs
- src/db/util.rs
- src/server/test.rs
- src/web/extractors.rs
Co-authored by: Phil Jenvey <pjenvey@underboss.org>
Issue #74
> feat: refactor sync timestamp

- src/db/mock.rs
- src/db/mod.rs
- src/db/mysql/models.rs
- src/db/mysql/test.rs
- src/db/params.rs
- src/db/util.rs
- src/server/mod.rs
- src/web/extractors.rs
- src/web/handlers.rs
- src/web/middleware.rs
Most handler functions now have the appropriate header added. The
precondition middleware returns the request early if the modified
header and database differ.
Closes #78
> feat: add precondition check middleware and handler headers

- src/db/mock.rs
- src/db/mod.rs
- src/db/mysql/models.rs
- src/db/mysql/pool.rs
- src/db/mysql/test.rs
- src/db/params.rs
- src/db/results.rs
- src/db/util.rs
- src/server/test.rs
- src/web/extractors.rs
- src/web/handlers.rs
- src/web/middleware.rs
also:
- ensure db middleware rolls back errors that don't trigger the response
method being called and rolling back for us
- fix ttl handling (the come in as seconds not milliseconds)
- add Debug to db traits
Issue #18
> feat: add get_bso_ids for full=false

- Cargo.toml
- src/db/error.rs
- src/error.rs
Fixes #90.
These are both things I had to fix recently in fxa-email-service, I presume we want to do the same here.
* In b2935f5, I stop capturing every error in Sentry because it's too noisy. Currently the only 500 errors we return are from the db error module, so I moved the capture into there.
* In 9d99c01, I include debug symbols in the release builds so that Sentry can include line numbers in stack traces.
@bbangert @pjenvey r?
> Two tiny tweaks for Sentry

- README.md
- src/db/error.rs
- src/db/mod.rs
- src/db/mysql/models.rs
- src/db/mysql/pool.rs
- src/db/mysql/test.rs
- src/error.rs
- src/server/test.rs
- src/web/handlers.rs
also:
- switch Db to return ApiErrors so they're rendered correctly
- hide the awful ergonomics of matching NotFound errors behind methods (for now
at least)
Closes #93
> fix: 404 on deletes of non existent individual bsos

- src/error.rs
- src/server/test.rs
- src/web/error.rs
- src/web/extractors.rs
Fixes #76, returning a 415 when the `Content-Type` header is wrong.
@pjenvey @bbangert r?
> fix: return a 415 for unsupported content-type headers

- src/server/mod.rs
- src/web/middleware.rs
Fixes e2e tests that verified the X-Last-Modified header should always
be set. Also fixed issue with 304 returning content without a content
type when it shouldn't return any content at all.
Closes #96
> feat: always set last-modified header, don't add content for 304

- src/db/mysql/batch.rs
- src/db/mysql/models.rs
- src/db/mysql/test.rs
- src/db/params.rs
- src/error.rs
- src/web/error.rs
- src/web/extractors.rs
- src/web/handlers.rs
- src/web/middleware.rs
Extractors now use proper limits from the state object. BSO handling
during deserialization/validation matches Python more closely.
Closes #97
> feat: fix extractors, middleware for e2e tests

- src/db/util.rs
- src/server/mod.rs
- src/web/middleware.rs
to match the level of timestamp precision. also have its middleware run first
to match python
> fix: use SyncTimestamp for sane WeaveTimestamp comparisons

- src/db/mock.rs
- src/db/mod.rs
- src/db/mysql/batch.rs
- src/db/mysql/models.rs
- src/db/util.rs
- src/error.rs
- src/main.rs
- src/server/mod.rs
- src/server/test.rs
- src/web/extractors.rs
- src/web/handlers.rs
- src/web/middleware.rs
Closes #105, #86
and a cargo fmt in a separate commit
> fix: add the batch extractor + handler

- .circleci/config.yml
- Dockerfile
- docker-compose.e2e.yaml
- docker-compose.yaml
- include build + test in the same job to avoid saving large artifacts
in between
- run e2e tests via docker-compose in a separate job. we're already
saving the docker image (which is a smaller artifact) for the deploy
job anyway
Closes #121
> test: run unit & e2e tests on circleci

- src/server/test.rs
- src/web/extractors.rs
but ignore modified. fix batch bsos to also ignore modified
Closes #111
> fix: reject unknown fields in PUT bso

- src/web/extractors.rs
- src/web/middleware.rs
Database locking failures can cause intermittent integration test
failures. The errors appear to get lost on the way out and eventually
get resolved to "Unexpected Db error". This logs the locking failure at
the time of occurrence, at least.
Issue #146
> feat: Add debugging to track database locking failures.

- Cargo.toml
- src/db/util.rs
- src/server/test.rs
via serde_json's arbitrary_precision feature
Closes #153
> fix: persist timestamps' decimal place precision through json

- Cargo.lock
- Cargo.toml
to support more openssl versions
Closes #163
> chore: bump to latest mozsvc-common

- Cargo.lock
- src/db/spanner/models.rs
- src/db/spanner/pool.rs
and quiet some rustc/clippy warnings
per RUSTSEC-2019-0011
> chore: bump to latest memoffset (crossbeam-epoch)

- Cargo.lock
- Cargo.toml
- db-tests/Cargo.lock
- src/db/spanner/models.rs
- src/db/spanner/support.rs
- spanner sql requests go through a builder with a python
client/rustyspanner like API
- google-api-rs response strings are wrapped to protobuf's Value type
(which the new SDK returns)
Issue #195
> refactor: abstract over much of our google-apis-rs usage

- .circleci/config.yml
- Cargo.lock
- Cargo.toml
- Dockerfile
- README.md
- db-tests/Cargo.lock
- db-tests/Cargo.toml
- src/db/error.rs
- src/db/mysql/models.rs
- src/db/spanner/manager.rs
- src/db/spanner/models.rs
- src/db/spanner/support.rs
- src/db/spanner/test_util.rs
- src/main.rs
- src/server/test.rs
- src/settings.rs
- src/web/auth.rs
- src/web/middleware.rs
I've setup a temporary deploy key for circleci to my github fork of the new client libs. So circleci can manually clone it and we use it as a path dependency
Closes #195, #201
> feat: Integrate the grpc spanner lib and fix e2e tests

- README.md
Adding details about need to install go to support the newly added grpc lib.
> docs: include details on golang requirement in setup instructions

- src/db/spanner/batch.rs
- src/db/spanner/support.rs
There are a few type errors that need to be fixed, but I think the general approach is correct.
This assumes that the batches table has a new "timestamp" field, which I added to the test database. Since id is used as part of the primary key, it can't contain duplicates. The code generates a unique timestamp for every bso in the batch to use as an id, but then selects based on the timestamp field instead of the id field.
> Fix batch handling on spanner by using multiple records instead of one.

- src/db/spanner/models.rs
> fix: correct mistaken GROUP BY fxa_kid (vs userid)

- spanner-2019-10-01.ddl
- src/db/spanner/batch.rs
- src/db/spanner/models.rs
needs #246 merged first
it's deployed on the `sync_schema` database
> refactor: cleanup spanner's schema

- PULL_REQUEST_TEMPLATE.md
Once merged, this *should* get automatically picked up by Github when opening new PRs in this repo. Let me know if there's anything else you think would make sense to have as a default here.
> chore: adding initial PR template

- .circleci/config.yml
ensuring workflow steps read artifacts from the right place
> chore: fix cache key to include CIRCLE_TAG

- README.md
Issue [251](https://github.com/mozilla-services/syncstorage-rs/issues/251)
> docs: add info on how to connect to Sentry locally

- tools/spanner/README.md
- tools/spanner/purge_ttl.py
- tools/spanner/write_batch.py
Add a set of python based tools for managing data in the spanner
database.
Issue: #119, #284
> feat: add spanner tools

- src/logging.rs
- src/main.rs
This fix routes logging messages through MozLog-json. The
`human_logs=TRUE` option returns human readable logs (like the previous
logging).
Closes #285
> bug: send logging output to MozLog

- src/web/middleware.rs
If the url is "/__heartbeat__", "/__lbheartbeat__", or "/__version__", don't run middleware, thus allowing the heartbeat to survive even if the db is refusing connections.
> Fix #296 Exempt dockerflow from middleware

- src/server/test.rs
- src/web/auth.rs
- src/web/extractors.rs
This patch replaces the hand rolled header parsers with ones from
actix_web. They're not perfect, but they're also someone else's
problem.
Closes #294
> feat: use actix_web header parsers

- db-tests/src/batch.rs
- spanner-2019-10-01.ddl
- src/db/mock.rs
- src/db/mod.rs
- src/db/mysql/batch.rs
- src/db/mysql/models.rs
- src/db/params.rs
- src/db/results.rs
- src/db/spanner/batch.rs
- src/db/spanner/batch_commit_insert.sql
- src/db/spanner/batch_commit_update.sql
- src/db/spanner/models.rs
- src/db/spanner/support.rs
- src/server/test.rs
- src/web/extractors.rs
- src/web/handlers.rs
mimicing the python implementation's moreso
- adds a batch_bso table for individual bsos
- batch/batch_bso now interleave in the user's split
- commit's work happens via DML statements
- special cases a new batch for a fresh collection w/ a "tombstone" like ("pre
birth stone"?) modified timestamp in user_collections. other queries filter
it out
- moves batch id's encoding for the client into the Db layer: mysql continues
base64ing its numeric batch id, whereas spanner simply uses a Uuid (in
simple/hex format)
Closes #299
> feat: rearrange the batch impl

- spanner-2019-10-01.ddl
- src/db/spanner/batch.rs
- src/db/spanner/batch_commit_insert.sql
- src/db/spanner/batch_commit_update.sql
- src/db/spanner/models.rs
- src/db/spanner/support.rs
- tools/spanner/purge_ttl.py
- tools/spanner/write_batch.py
- always prefix primary key names with their table name (id -> bso_id,
collection_id). a best practice in spanner, as when tables
interleave, their shared id names must always match
- bso -> bsos (every other table name's plural)
- give batches an expiry index
Closes #313
> refactor: schema renames (again)

- Dockerfile
- spanner_config.ini
*NOTE* this introduces a configuation.ini file. Unfortunately,
the config parser does not allow a single `limit` sub-setting
to be specified from the environment or command line, but does
allow a single sub-setting from within a configuration file.
Closes #298
> feat Limit max_total_records due to spanner mutation limit

- src/server/metrics.rs
> bug: Metric timer should use millis

- spanner-2019-10-01.ddl
- spanner_config.ini
- src/web/handlers.rs
reduce to 1999 (19990 mutations) accounting for batch commit's extra
mutations: touch_collection (+1) and batch delete (+2: for delete +
BsoExpiry update)
schema: don't restrict bso_id in the schema (this was already applied to
stage and fakeprod)
and cleanup old NLL restriction gone in newer rust versions
Closes #333
> fix: correct max_total_records

- spanner-2019-10-01.ddl
- src/db/spanner/batch.rs
- src/db/spanner/models.rs
- src/db/spanner/support.rs
- src/web/handlers.rs
write the pending bsos immediately when committing a batch instead of
queueing them in the batch_bsos, so we don't pay twice for their
mutations
also
- optimize batch append to insert all items in one write
- interleave BsoExpiry w/ user_collections
Closes #333, #318
& some minor cleanup in a separate commit
> fix: optimize batch commit mutations 

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
Creating a release so we can test out [this fix](https://github.com/mozilla-services/syncstorage-rs/pull/353) against prod. Also added releasing instructions to README (let me know if I missed anything).
Read the bits added to README.
N/A
> chore: tag 0.1.8

- src/db/mysql/test.rs
- src/web/extractors.rs
Added logic to prevent mysql tests from running when tests use a Spanner DSN
run `cargo test` with  `SYNC_DATABASE_URL` pointing to a Spanner DSN 
Closes #360
> bug: Don't run mysql tests when testing spanner.

- src/db/spanner/models.rs
- src/db/spanner/pool.rs
- src/settings.rs
- src/web/error.rs
- src/web/extractors.rs
- src/web/middleware.rs
- tools/hawk/README.md
This adds some additional debug around handling BSOs to try and identify
the source of the server returning 400 on PUT `/1.5/xxx/storage/meta/global`.
There may be a related client bug where it's sending no BSO on a
meta/global PUT, thus the very specific fix.
* also new clippy, new crap to clean up.
Since we don't have a lot of tests that check full path, the test I've been using is to use `/tools/hawk/make_hawk_token.py` to generate a valid `Authorization` header
then call 
```
curl -v -X PUT "http://localhost:8000/1.5/1/storage/meta/global" \
-H "content-type: application/json" \
-H "Authorization: $AUTH"
```
Issue #342
>  feat: Handle empty bso body on /meta/global

- tools/hawk/make_hawk_token.py
Currently, it is possible to change the uri being signed by make_hawk_token using the --uri command line argument, but not possible to change the http method. This patch adds a --method flag.
`cargo run` in one terminal
`venv/bin/python make_hawk_token.py --method PUT --uri /1.5/1/storage/meta/global --secret=$SYNC_MASTER_SECRET --as_header > auth.txt`
```curl -v -X PUT "http://localhost:8000/1.5/1/storage/meta/global"     -H "content-type: application/json"     -H "Authorization: `cat auth.txt`"```
> Add a --method parameter to tools/hawk/make_hawk_token.py

- shell.nix
Nix is a distribution independent package manager.
By providing this file user of nix get automatically all
required build dependencies by sourcing default.nix via a tool called
nix-shell. This should lower the entry barrier when setting up a
build environment.
Nix is also used in other places in Mozilla: https://github.com/mozilla/nixpkgs-mozilla
```
$ nix-shell --command 'cargo build'
```
No issues related to this
> provide shell.nix

- tools/examples/put.bash
I was running this script locally and noticed it failing all of a sudden. Looks like a recent change to the [hawk header script](https://github.com/mozilla-services/syncstorage-rs/pull/364/files#diff-4e6a513ac3e7f901d7ae6713da762cafR123) added an extra key, causing this script to fail.
1. Outside of this branch, try running the `put.bash` script following [these instructions](https://github.com/mozilla-services/syncstorage-rs/tree/master/tools/examples). See it fail, and see we're passing something like this: ` Authorization: Authorization: Hawk id=` for the Auth header.
2. Now, checkout this branch, try again. You should get a 200.
Closes [#370](https://github.com/mozilla-services/syncstorage-rs/issues/370).
> fix: remove duplicate header key from example script

- src/db/spanner/batch.rs
- src/db/spanner/models.rs
- src/web/extractors.rs
a pile of of hacks which we'll hopefully revert shortly
Issue #333
Also see https://sentry.prod.mozaws.net/operations/syncstorage-prod/issues/6621760/events/36079823/ for what this is specifically after
> feat: add temporary sentry tags for the mutation limit issue

- spanner_config.ini
- src/db/spanner/models.rs
- src/web/handlers.rs
and remove the potential, redundant touch_collection on batch commit
recalculating the mutations (see adca8d67):
- 4 for touch_collection: always an UPDATE on batch commit (due to
pretouch_collection). we thought this cost 1 but it's probably 4 (see
#333)
- 19992 (1666 max_total_records * 12, for the UPDATE case, see #333) for
the mix of post_bsos and batch_commit
- 2 for batch delete (1 for the delete and 1 BsoExpiry update)
total: 19998
Closes #333
> fix: lower max_total_records per batch_commit_update costs

- README.md
In tandem with [this syncserver PR](https://github.com/mozilla-services/syncserver/pull/186), I'm working on making it easier to understand how to run syncstorage-rs locally from with Firefox.
I've added instructions here for running against MySQL. I'll come back and do another pass against a spanner instance in the future.
I **did** notice a few oddities about this, ie warnings in the logs, etc. I also noticed that my payload_size always gets set to "0". I figure that this is at least better than not being able to run this locally at all, hence me opening a PR now; it might be worth a future pass though to poke around there a bit more.
1. Follow the instructions I've added here. 
2. Confirm you are also able to get this working locally. Here's [what I'm …
> docs: add instructions on how to connect to local firefox

- Dockerfile
force cargo install to use Cargo.lock
Closes #378
> chore: force cargo install to use Cargo.lock

- README.md
I realized that I found this out through some trial and error the other day but forgot to document. Adding now.
Follow the instructions that I've added here in the README. Make sure you too can get an error to appear in Sentry from your local machine.
Closes [#381](https://github.com/mozilla-services/syncstorage-rs/issues/381).
> docs: add more detailed sentry testing info

- Cargo.lock
- Cargo.toml
- README.md
- db-tests/Cargo.lock
- db-tests/src/batch.rs
- db-tests/src/support.rs
- src/db/error.rs
- src/db/spanner/models.rs
- src/error.rs
- src/main.rs
- src/server/metrics.rs
- src/server/mod.rs
- src/server/test.rs
- src/web/auth.rs
- src/web/error.rs
- src/web/extractors.rs
- src/web/handlers.rs
- src/web/middleware.rs
- src/web/mod.rs
- src/web/tags.rs
Not a super fan of this. It might be better as middleware, but that's
not always defined when we make sentry error calls. Passes a `Tags` structure around that contains the tags that will be added to sentry and metrics calls.
There is an included unit test to check default tag generation. 
In addition, there is now a new test endpoint called `/__error__` that will generate a sentry error containing the ua tags. (see https://sentry.prod.mozaws.net/operations/syncstorage-dev/issues/6888305/ for sample output)
When running tests, note that the following tags should be added to sentry and metric calls:
* ua,os,ver
* ua.os.family
* ua.browser.ver
* ua.name
* ua.browser.family
* uri.path
* uri.method
Issue: [#329](https://github.com/mozilla-services/syncstorage-rs/issues/329)
> bug: add tag info to sentry error messages

- .dockerignore
- .gitignore
- Dockerfile
- Makefile
- README.md
- docker-compose.e2e.yaml
- docker-compose.yaml
- src/db/spanner/models.rs
- tools/spanner/README.md
As per a recent Ops request, adding python to our docker image so we can automate the purge_ttl script. We've got [a followup](https://github.com/mozilla-services/syncstorage-rs/issues/385) to rewrite this in Rust so we can remove the python dep, but I don't think it's worth it right now.
While I was in here, I added a few details to the README on running this locally via Docker. I also bumped our Rust version to 1.40, and made a few small changes to the dockerfile to try to reduce it's size a bit.
1. Follow the instructions I'm adding in this PR to the README for running via docker locally.
2. Once it's running, do a `docker ps` to grab your container id.
3. `docker exec -it {CONTAINER_ID_HERE} bash` - enter container, type `python3 tools/spanner/purge_ttl.py` - You should see an error …
> chore: add python to docker image & bump rust version

- Dockerfile
- tools/spanner/purge_ttl.py
Add start/stop/duration logging for the purge_ttl.py script as well as post the durations timings to a
statsd server (defaults to `localhost:8125`, overrides with env variables `STATSD_HOST:STATSD_PORT`
set env variables for:
```
export GOOGLE_APPLICATION_CREDENTIALS=path/to/credentials.json
export SYNC_DATABASE_URL=<url-to-database>
```
[optional] Listen for statsd in another shell:
```
nc -u -l 8125
```
Then execute:
```
python3 ./tools/spanner/purge_ttl.py
```
> Add basic logging to stdout and statsd metrics for purge_ttl.py

- src/web/middleware/precondition.rs
Closes #393
Use `HttpResponse::build(status)` instead, which is clearer.
This is a code cosmetic change.
Closes #393
> bug: Don't use HttpResponse::Ok().status(status)

- src/server/metrics.rs
- src/web/middleware/sentry.rs
- src/web/tags.rs
Remove the `uri.path` from default Tags.
Unit tests were modified.
Closes #408
> bug: Don't report `uri.path` to Metrics

- src/server/metrics.rs
- src/web/tags.rs
Closes #404
Sentry flags empty strings `""` as an error, so filter those out.
unit tests include `no_empty_tags()` which tests that "ua.os.ver" is not set for a UA that does not contain an OS version.
Closes #404
> Filter out "" values from sentry

- tools/spanner/count_users.py
Python script to count distinct `fxa_uid`s found in the `user_collections` table.
set env variables for:
```
export GOOGLE_APPLICATION_CREDENTIALS=path/to/credentials.json
export SYNC_DATABASE_URL=<url-to-database>
```
[optional] Listen for statsd in another shell:
```
nc -u -l 8125
```
Then execute:
```
python3 ./tools/spanner/count_users.py
```
n/a
> feat: script to count total users in spanner

- src/db/error.rs
- src/error.rs
- src/web/middleware/sentry.rs
- src/web/tags.rs
filter out UID and batch numbers from URI.
This drops the first two path elements from the URI as well as masks any large hexidecimal identifier that may appear in the URI parameters. This should retain enough diagnostic information to be useful without causing overload for sentry.
While running normal testing note that the `uri.path` metric goes from something like:
`/1.5/135772380/storage/history?batch=5ef59eae10244edc90935bab2ffea0f0&commit=true`
to 
`storage/history?batch=###&commit=true`
Closes #420
> bug: filter out variable data from URI metric

- Cargo.toml
Seeing less log messages output in `--release` mode
Closes #426
> feat: restrict release mode logging to ERROR

- .circleci/config.yml
reverts #204
Drop the rust changelog CI job.
We're (foxsec/secops) working on an alternative that doesn't run in CI and provides more historical and cross-repo data, but it will break the current CI job interface.
The rust-changelog CI job should no longer run in CI. Other tests should still pass.
None.
> ci: rm rust dependency diff

- src/db/spanner/models.rs
- src/db/spanner/support.rs
- src/web/extractors.rs
Convert miscellaneous spanner database functions to async/await, including underlying shared code like .execute(.
Closes #436.
> Fix #436 Convert misc db functions to async/await

- tools/user_migration/migrate_user.py
Alter the migration table to use SmallInt rather than string. Also add state transitions during migrations.
* Remove the `migration` table if it already exists (there is no migration path to update since this table is new).
* run a test migration as noted in https://github.com/mozilla-services/syncstorage-rs/pull/401
Closes #428 
(see also https://github.com/mozilla-services/server-syncstorage/pull/144)
> bug: convert migration state to smallint

- db-tests/Cargo.lock
- src/db/spanner/models.rs
- src/db/spanner/support.rs
This branch converts all the methods related to collections.
-    get_collection_timestamp
-    get_collection_timestamps
-    get_collection_counts
-    get_collection_usage
-    delete_collection
- map_collection_names
- load_collection_names
Closes #434.
> Fix #434 Convert db collection calls to async await.

- src/db/spanner/models.rs
- src/db/spanner/support.rs
Convert database bso calls to async await
-    delete_bso
-    delete_bsos
-    get_bsos
-    get_bso_ids
-    get_bso
-    get_bso_timestamp
-    put_bso
-    post_bsos
- touch_collection
- bsos_query_sync
- create_collection
- get_or_create_collection_id
All tests should pass. (Integration tests may currently fail, but we'll fix this up after all the db async await work has landed. One more pr for that after this one.)
Closes #433.
> refactor: Fix #433 Convert database bso calls to async await

- src/db/spanner/batch.rs
- src/db/spanner/models.rs
Convert db batch calls to async await.
-    create_batch
-    validate_batch
-    append_to_batch
-    get_batch
-    commit_batch
- delete_batch
- do_append
- pretouch_collection
Closes #435.
> refactor: Fix #435 Convert db batch calls to async await.

- src/db/spanner/models.rs
The db tests became broken by a recent async await commit because there was a special, db-tests only function that didn't get converted to async. This uses the old synchronous implementation when running in db-tests.
All tests should pass against spanner.
Closes #459.
> fix: Fix #459 db-tests on master

- .circleci/config.yml
- src/db/mysql/models.rs
- src/db/spanner/models.rs
When the client does not pass a sort argument, the python server defaults to sort by oldest. The rust server defaults to sort by nothing, causing bug #468.
The STR in the bug should show that X-Weave-Next-Offset when fetching collections with more than 1000 elements. (lina should probably test it)
Closes #468.
> fix: GETs with a limit and no sort never advance X-Weave-Next-Offset

- Cargo.toml
To help us avoid future issues with folks using the wrong rust version, I'm adding [this field](https://github.com/rust-lang/rfcs/pull/2495) into our cargo.toml.
Well...the main thing to review is: did I get the version right? :) I picked 1.39.0 given that I at least know for sure that we're depending on async/await which was introduced then. Anything that rolled into Rust stable afterwards we're requiring?
Closes [#424](https://github.com/mozilla-services/syncstorage-rs/issues/424).
> chore: add minumum supported rust version

- src/web/extractors.rs
fix: relax MAX_TTL to 9 digits
The forms collection defaults to a 3 year TTL which we currently reject. This puts us in line with the Sync 1.5 spec's full 9 digits.
Merging this into the 0.2 release branch so we cut a 0.2.5 and ship this out ASAP w/ the 0.2.4 fix.
new test_max_ttl unit test or test using forms.
Closes #480
> fix: relax MAX_TTL to 9 digits

- Cargo.toml
This reverts [a PR](https://github.com/mozilla-services/syncstorage-rs/pull/475/commits/9740221aea93f4872e6369522aa55f0a93c3742a) that added a config change that it looks like was never actually implemented in Rust. 
Looks like I was so excited to find the config value I was hoping for, I missed the fact that what was merged was [an rfc](https://github.com/rust-lang/rfcs/pull/2495) not actual [support for it](https://github.com/rust-lang/rust/issues/65262). 
1. `make run` against master. See this warning `warning: unused manifest key: package.rust`
2. `make run` in this branch. Verify no more warning.
References #424
> fix: revert unsupported config change

- src/db/mysql/models.rs
- src/db/spanner/models.rs
- src/db/spanner/support.rs
Convert erect_tombstone to async/await, nd in the process, remove all the spanner synchronous support code. The spanner backend is now truly 100% sync code free.
Closes #463.
> fix: Convert erect_tombstone to async/await

- .circleci/config.yml
Presumably, master only changes with a PR merge.  This circleci config change causes circle to build an image for every commit on master, it makes the docker tag equal to the git commit sha1.  The downstream automation will then deploy to the development environment when the docker tag looks like a commit sha1 (matches the regex `/[0-9a-f]{40}/`).
I think the `if echo "${CIRCLE_BRANCH}" | grep '^feature\..*' > /dev/null; the` block is not used and can be deleted.
When a release is tagged, the following block will cause the docker tag to match the git tag.  The downstream automation will deploy tags that don't match the sha1 type regex to stage:
```
if [ -n "${CIRCLE_TAG}" ]; then
DOCKER_TAG="$CIRCLE_TAG"
fi
```
Merge to master and see if our deployment is triggered.
Related to [Create …
> Build images when PRs are merged to master

- Cargo.toml
- src/web/tags.rs
Add `KV` trait for `Tags` struct to simplify logging its content.
For example, in `extractors.rs` instead of 
```rust
warn!("⚠️ Missing BSO: {:?}", uri.path();
"ua.os.family" => tags.get("ua.os.family"),
"ua.browser.family" => tags.get("ua.browser.family"),
"ua.name" => tags.get("ua.name"),
"ua.os.ver" => tags.get("ua.os.ver"),
"ua.browser.ver" => tags.get("ua.browser.ver"));
```
this snippet can be used:
```rust
warn!("⚠️ Unexpected BSO URI: {:?}", uri.path(); tags);
```
Closes #387 .
> feat: Add KV trait for Tags

- README.md
The endpoint was wrongly rendered as bold `heartbeat` instead of
`__heartbeat__`. Let's fix this by escaping the `_`s.
Closes #496.
> doc: fix URL rendering in README

- spanner-2019-10-01.ddl
There should be a visual separation between `insert into` and `create
table` commands. Also, `insert into`s should be run only after `create
table`s. Let's move `insert into` statements to the bottom to convey
the same.
Closes #473
> chore: move `insert into` to the bottom of ddl

- src/db/spanner/models.rs
correct the test version of post_bsos
to call into the test version of put_bso
The db::post_bsos test should now pass (under Spanner)
Closes #533
> fix: correct the test version of post_bsos

- Dockerfile
- tools/spanner/purge_ttl/src/main.rs
and improve the missing db env error message
also don't package purge_ttl's target/ into the docker
(merging into the 0.2b release branch)
run w/ e.g. STATSD_HOST=localhost
Closes #548
> fix: allow hostnames for STATSD_HOST

- .circleci/config.yml
- src/db/mysql/models.rs
- src/web/extractors.rs
Cherry-pick the MAX_TTL fix into 0.2.1 (and ba481089 + acadfc80 for ci). We'll tag/deploy this as a 0.2.1.1 to be on the safe side, then deploy the GET collection ordering fix separately.
test_max_ttl unit test
Closes #480
> cherry-pick fix: relax MAX_TTL to 9 digits

- src/db/mysql/models.rs
- src/db/spanner/models.rs
- src/web/extractors.rs
and disable encoded offsets (which rely on the sort order) for now
(only for the 0.2 branch)
Sorry for another round of review to get this out, I decided to go forward on top of the 0.2.8 release (release/0.2b branch) vs the older 0.2.1 tag.
All tests, including e2e, pass
Closes #559
> feat: revert the GET collection sort order (c95f2ff)

- src/server/metrics.rs
- src/web/extractors.rs
- src/web/handlers.rs
Refactor how `Tags` content is logged. Due to KV trait being implemented for this struct, it can be passed to `slog` as is without need to log each of its key/value individually. See example in #493 `Testing` section.
Nothing should change in log messages, except `uri.method` tag being added.
Closes #503 .
> refactor: Refactor Tags logging by utilising KV trait

- Dockerfile
Due to a change in the root image we use, the `build_essential` package was not installed. This prevented several additional modules from loading because they could not compile subcomponents.
CircleCI tes
Closes #572
> bug: add build_essential package to Dockerfile.

- Dockerfile
Now that purge_ttl has been ported to rust, we may remove the python dependency from the dockerfile.
Tests should pass.
Fixes #567
> refactor: Remove python dependency from the dockerfile.

- src/server/mod.rs
- src/web/extractors.rs
- src/web/mod.rs
- src/web/tokenserver.rs
This includes a route for GET /1.0/sync/1.5, an extractor for it, and an async handler as well as a blocking handler in case blocking libraries need to be used.
Tests should pass.
This closes an issue in another repository, https://github.com/mozilla-services/tokenserver-rs/issues/8
> Commit a skeleton for the tokenserver.

- README.md
Adds some more syntax highlighting to readme: `sql`, `yml`, and `ini`
Uh, I don't know; maybe test if the syntax highlighting gives you a feeling of satisfaction
None (or at least I don't think so)
> Add some more syntax highlighting to readme

- Dockerfile
- src/server/mod.rs
- src/server/test.rs
- src/web/middleware/mod.rs
- src/web/middleware/rejectua.rs
to prevent them from triggering a bug that crashes them
and update Dockerfile builder to latest rust
- New ios unit tests pass
- firefox-ios doesn't crash
Testing against a local syncstorage, firefox-ios in the simulator crashes without this change, log:
```
2020-04-07 11:55:35.803 [Debug] [ClientsSynchronizer.swift:195] processCommandsFromRecord(_:withServer:) > Processing commands from downloaded record.
2020-04-07 11:55:35.803 [Debug] [ClientsSynchronizer.swift:279] maybeUploadOurRecord(_:ifUnmodifiedSince:toServer:) > Should we upload our client record? Caller = false, expired = false.
2020-04-07 11:55:35.804 [Debug] [ClientsSynchronizer.swift:353] applyStorageResponse(_:toLocalClients:withServer:notifier:) > Running 0 commands.
Fatal error: Unexpectedly found nil while unwrapping an …
```
> feat: reject firefox-ios < 20 w/ a 503

- src/db/mysql/models.rs
- src/db/spanner/models.rs
- src/web/extractors.rs
Change struct Offset to use u64 offset instead of i64.
?
Closes #414
> refactor: use u64 instead of i64 for Offset.offset

- Cargo.toml
Followup to #583 otherwise:
``
error: `cargo run` could not determine which binary to run. Use the `--bin` option to specify a binary, or the `default-run` manifest key.
available binaries: purge_ttl, syncstorage
``
cargo run
> chore: default-run syncstorage

- src/web/handlers.rs
Convert actix-web front-end calls from Futures style into async/await style.
This patch doesn't change any behavior and running `cargo test` should pass all tests.
#541, #439
Closes [#541](https://github.com/mozilla-services/syncstorage-rs/issues/541).
> refactor: Convert misc actix-web frontend calls to async await 

- src/web/handlers.rs
don't turn them into 404s
Merging into release/0.3 branch, then I'll cut a 0.3.1 for solely this.
Difficult to test this behavior (requires generating an error from the db layer other than BsoNotFound)
Closes #599
> fix: restore delete_bso's handling of errors

- src/bin/purge_ttl.rs
- src/db/error.rs
- src/db/mysql/batch.rs
- src/db/mysql/models.rs
- src/db/mysql/test.rs
- src/db/tests/support.rs
- src/logging.rs
- src/server/test.rs
- src/web/auth.rs
- src/web/error.rs
- src/web/extractors.rs
This code attempts to fix the purge_ttl timeout by grabbing all the ids to delete and chunking them up into batches of 1000.
For testing this, build it with:
`cargo install --path . --bin purge_ttl --locked --root output`
Then run it with:
`RUST_LOG=info GOOGLE_APPLICATION_CREDENTIALS=... SYNC_DATABASE_URL=... output/bin/purge_ttl`
You will need an appropriate credentials file and database url to a spanner database. First of all, it should be able to run and not have any errors deleting 0 items.
Then, if some records are added to the bsos and batches tables, with expired expires timestamps, running it should print info about how many records were deleted. Examining spanner should show that they were actually deleted.
To add records to the tables, I modified the load tester to have a 100% …
> Fix purge ttl timeout

- tools/user_migration/gen_bso_users.py
- tools/user_migration/gen_fxa_users.py
- tools/user_migration/migrate_node.py
More operational fixes and features
* fixed typos in files
* added `--start_bso`, `--end_bso` to `gen_bso_users.py`
* added `bso_num` arg (same as `--start_bso=# --end_bso=#`) to `migrate_node.py`
* `gen_bso_users.py` takes same `bso_users_file` template as `migrate_node.py`
TBD
Issue #401
> User migration5

- src/db/mock.rs
- src/db/mod.rs
- src/db/mysql/pool.rs
- src/db/results.rs
- src/db/spanner/pool.rs
- src/server/mod.rs
kill the mislabeled pool get metric for now (fixes it repeatedly
emitting)
Run `nc -lu -p 8125` alongside syncstorage-rs 
Closes #555, #406
> feat: emit Db pool metrics periodically

- README.md
from https://github.com/Emmanuel-Melon/syncstorage-rs/tree/update-docker-instructions
to replace #595
N/A
N/A
> docs: Update instructions for running syncstorage-rs via Docker

- src/db/mod.rs
- src/server/mod.rs
include a hostname tag w/ pool metrics
so we can distinguish between nodes
Against the `release/0.3` branch
Run `nc -lu -p 8125` alongside syncstorage-rs 
Closes #555
> feat: include a hostname tag w/ pool metrics

- src/db/mock.rs
- src/db/mod.rs
- src/db/mysql/batch.rs
- src/db/mysql/models.rs
- src/db/spanner/models.rs
- src/web/handlers.rs
* elevated `begin()` to an interface call to allow `delete_all` the
ability to lock the database.
* added `begin_async()` wrapper to mysql & mock to mirror spanner function
* added `begin()` call to `delete_all`
cargo test should pass for both mysql and spanner.
Closes #615
> feat: add async to `delete_all`

- src/db/error.rs
- src/db/mysql/models.rs
- src/db/spanner/models.rs
- src/error.rs
- src/web/middleware/sentry.rs
* Added new metric "db.conflict"
* Added new error method `is_reportable()` for future error filtering.
Unfortunately, testing requires  a db conflict write and, metrics and sentry reporting. A `debug!()` line does include the error that is not being directly reported to Sentry.
Closes #614
> feat: Don't report Conflict errors to sentry

- README.md
Update docs per renaming our local sentry project after adding a formal dev env
> docs: update per sentry dev's rename to local

- src/db/spanner/batch_commit_insert.sql
- src/db/spanner/batch_commit_update.sql
- considering expiry causes potential AlreadyExists errors (as we
attempt to INSERT new records that already exist albeit in an expired
state), though these errors are only temporary until the expired data
is purged
- *not* considering expiry seems less correct: we can resurrect expired
data. but this matches Python syncstorage's behavior
- in practice the AlreadyExists errors mostly happen on the history
collection
unit/e2e tests passing
Issue #625
> fix: don't consider expiry during batch commit

- src/db/error.rs
as of #632 they should no longer occur. In case they do for whatever
reason, they should go to sentry
Unit/e2e tests pass
Closes #633
> fix: don't classify AlreadyExists as a ConflictError

- tools/user_migration/migrate_node.py
Closes #636
Check if `bso_num` is not empty, not just `false`
`migrate_node.py --bso_num=0` should only run data for users in the `bso0` database.
Closes #636
> bug: Make `bso_num` in migrate_node less truthy

- src/bin/purge_ttl.rs
- src/db/mysql/test.rs
- src/web/middleware/db.rs
- src/web/middleware/mod.rs
- src/web/middleware/precondition.rs
- src/web/middleware/sentry.rs
Actix currently discards any errors generated in the middleware. You are
supposed to pass them in the body or some similar sub-optimal means.
Not a super fan of this approach, but basically, this patch attaches a
the error to the request or response extensions bucket. Since sentry is
also a middleware and gets run on every response, it sweeps the
request/response extension buckets and reports any errors it finds.
This has the downside that some context may be lost from the error (e.g.
I STRONGLY suspect the backtrace will be useless)
WIP:
Need to verify all middleware errors are being stored to extensions. 
`debug!` statements have been added in the sentry middleware to note if an error has been detected and logged. You can trigger one such error (Bad Hawk Id) by …
> feat: log messages from middleware to sentry

- .circleci/config.yml
Fix build errors for python spanner utils image
Run circleci
> fix: python image build needs stable docker git container

- tools/spanner/purge_ttl.py
- tools/spanner/requirements.txt
attempt to try and provide a way to allow the purge_ttl script to complete.
Adds arguments (ENV VARS):
--instance_id (INSTANCE_ID)  Spanner instance id
--database_id (DATABASE_ID)  Spanner database id
--sync_database_url (SYNC_DATABASE_URL) Spanner DSN
`spanner://instance/database`
--collection_ids (COLLECTION_IDS)
JSON formatted list of collections to limit deletions
e.g. `--collection_ids=123` limits to just collection 123
`--collection_ids=[123,456]` limits to both 123 & 456
default is all collections
May be used with the stage spanner database instance
Issue #631
> feat: add conditions, args to purge_ttl script

- Cargo.lock
- Cargo.toml
- src/db/mysql/models.rs
- src/settings.rs
- src/web/handlers.rs
and adjust ACTIX_THREADPOOL per the database_pool_max_size on mysql
tests pass under mysql
Closes #639
Closes #441
> fix: don't call begin twice for mysql's delete_all

- Cargo.lock
Fixes recompiling `grpcio-sys` on every build. See https://github.com/tikv/grpc-rs/issues/449
Only affects non-linux platforms. Run `cargo check` twice and it should only compile `grpcio-sys` once.
N/A
> Fix constant recompilation by upgrading grpcio-sys to 0.5.3

- tools/spanner/purge_ttl.py
Closes #707
Rounds down the expiry range to previous midnight
Note that records expiring post midnight are not deleted
Closes #707
> feat: limit purge ttl to prior midnight

- Cargo.lock
- src/db/mod.rs
- src/db/spanner/manager.rs
- src/db/spanner/models.rs
- src/db/transaction.rs
- src/web/extractors.rs
- src/web/handlers.rs
- src/web/middleware/precondition.rs
#692 was experiencing some very surprising performance regressions in some integration tests. These regressions have been narrowed down to a change in how DB transactions are handled in the branch. Previously the whole request was in one DB transaction. This was changed to only running the DB transaction in the handler. There were some middlewares/extractors directly accessing the DB pool, which is believed to be the cause of the performance regressions. This PR wraps those non-handler DB interactions in transactions, along with a few other fixes (ex. remove unsafe Send impl for SpannerDb).
All requests made during the `test_batch_ttl_update` integration test should take < 4 seconds. Previously, some requests took 15-20 seconds. Make sure you are using Spanner for this test.
N/A
> Fix performance issues in bb8 branch

- src/db/error.rs
- src/db/spanner/manager.rs
- src/db/spanner/models.rs
- src/db/spanner/pool.rs
- src/web/handlers.rs
- prefer a set vs vec of the existing bso_ids
- /info/configuration -> async fn
Further load testing
Closes #745
Issue #732
After implmenting this I'm a little less convinced it's actually needed as we *don't* establish connections that frequently with the Pooling, but it shouldn't hurt we can confirm its metric timings.
Also we discussed recycling connections after a certain number of uses but I recalled both r2d2 & bb8 default to a 30 minute Connection lifetime -- so they're pretty much doing something similar for us already.
> fix: defer grpc auth to actix-web's thread pool

- Cargo.lock
- Cargo.toml
- src/db/mysql/models.rs
- src/db/spanner/models.rs
- src/error.rs
- src/main.rs
- src/web/middleware/sentry.rs
Closes: 742
This will log all `is_conflict()` errors as a `db.conflict` metric from inside the sentry logging middleware.
NOTE: due to local compile requirements, sentry has been updated to 0.19, which required changes in the initialization. 
Please pay close attention to those as I believe they are correct, but appreciate better eyes.
Closes #742.
> feat: add metric for db conflicts

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Tagging release 0.5.4 ahead of the official Github tab.
We've had a ton of changes since an official tag + clog change. The only difference here is the addition of https://github.com/mozilla-services/syncstorage-rs/pull/758 since 0.5.3.
> chore: tag 0.5.4 release

- Cargo.toml
- src/error.rs
- src/web/middleware/sentry.rs
* Set grpcio feature `"openssl"` on ubuntu platforms to address seg faulting on startup due to combination of openssl and boringssl.
N/A
Issue #742
> dereference Data<> before calling `on_response()`

- src/settings.rs
- src/web/extractors.rs
Closes #762
Passing the default separator of "." can cause problems with some shells. It's better to use something like a double underscrore, which is more widely accepted.
run the application, specifying the `limits.max_post_records` set to some value, e.g.
`SYNC_LIMITS__MAX_POST_RECORDS=99 cargo run -- --config sync.ini`
You should now be able to see the "debug_client" value appear in the `/info/configuration` response:
```
> curl http://localhost:8000/1.5/1/info/configuration
{"max_post_bytes":2097152,"max_post_records":99,"max_record_payload_bytes":2097152,"max_request_bytes":2101248,"max_total_bytes":100000000,"max_total_records":10000,"debug_client":"1,123"}
```
Closes #762.
> bug: set config env separator to double underscore.

- src/error.rs
- src/web/extractors.rs
Closes #769
We were returning "17", we should return "14"
see https://github.com/mozilla-services/syncstorage-rs/pull/751
Closes #769.
> bug: Return WeaveError::OverQuota for over quota responses

- Cargo.toml
- README.md
removed Cargo's automagic feature detection that was less magical than expected.
Added comment to `.toml` and `README.md` addressing fix resolution for folks that hit the same error that required the feature detection.
Does it ~blend~ build and run?
Closes #774.
> bug: remove ubuntu target for grpcio 

- tools/spanner/purge_ttl.py
- Add `--mode`/`PURGE_MODE` to choose if `batches`, `bsos`, or `both` tables should be purged.
- Add `--expiry_mode`/`PURGE_EXPIRY_MODE` to choose if the expiry should be compared against `midnight` or `now`.
- Support serially deleting UID prefixes by regex, with `--uid_prefixes`/`PURGE_UID_PREFIXES`.
- This is a list of regex, ex. `[^[a-h],^[i-p]]`.
- Each entry is a separate purge run.
- This replaces `--uid_starts`.
- Change `--collection_ids`/`COLLECTION_IDS` from a JSON list to an "args" list (like `--uid_prefixes`).
Run against dev
Closes #735
Closes #743
> feat: More purge_ttl features

- Cargo.lock
- Cargo.toml
- src/db/mysql/models.rs
- src/error.rs
- src/main.rs
- src/server/test.rs
- src/settings.rs
- src/web/extractors.rs
includes latest rust clippy fixes and a sentry bump related to build issues
Co-authored-by: JR Conlin <jrconlin@gmail.com>
Should work just like the current prod version.
Closes #779
> feat: Backport `debug_client` opt

- src/db/transaction.rs
- src/web/handlers.rs
Always create a transaction when using `DbTransactionPool`. This avoids implicit transactions.
Not sure how the issue is/was detected, so not sure on testing.
Potential fix for #768
> fix: Avoid implicit transactions in DbTransactionPool

- src/db/mod.rs
- src/db/mysql/pool.rs
- src/db/results.rs
- src/db/spanner/manager/bb8.rs
- src/db/spanner/manager/deadpool.rs
- src/db/spanner/manager/mod.rs
- src/db/spanner/manager/session.rs
- src/db/spanner/models.rs
- src/db/spanner/pool.rs
- src/settings.rs
- src/web/extractors.rs
- ignore deadpool's Status::available negative values for PoolState
- kill no longer used DB_THREAD_POOL_SIZE
Stage load testing
Closes #794
You can review the deadpool change in its entirety (this commit and the previous) here: https://github.com/mozilla-services/syncstorage-rs/compare/7e526cb83...feat/794
> feat: cleanup the spanner pool managers

- tools/spanner/purge_ttl.py
* fix `fxa_uaid` typo
* fix `collection_ids` handler to deal with default empty ids.
* added `--dryrun` option which will NOT delete records from spanner.
the `--dryrun` flag will not send the PDML to spanner, so it can be useful for testing.
1) using a command like 
`GOOGLE_APPLICATION_CREDENTIALS=... venv/bin/python purge_ttl.py --dryrun` 
ensure that the output displays an output similar to:
```
...
{"datetime": "2020-08-24 15:19:24,202", "message": "Running: DELETE FROM batches WHERE expiry < TIMESTAMP_TRUNC(CURRENT_TIMESTAMP(), DAY, "UTC")"}
{"datetime": "2020-08-24 15:19:24,202", "message": "batches: removed 0 rows, batches_duration: 0:00:00.000001, prefix: "}
...
```
(note that there is no `REGEXP_CONTAINS` clause and no `collection_id` clause, and no command is run against …
> bug: fix purge_ttl advanced features

- README.md
- src/db/tests/support.rs
Normally, when running cargo test, the test transaction data is discarded. This makes debugging test state difficult. There is a use_test_transactions setting that can be overridden, but the tests then re-override your decision to force them on.
This branch exposes the variable using the SYNC_DATABASE_USE_TEST_TRANSACTIONS environment variable.
Also, it documents how to use this feature.
Running `SYNC_DATABASE_USE_TEST_TRANSACTIONS=false cargo test commit` should leave data in the mysql database.
Running `cargo test commit` should not leave anything in the database, as usual.
Closes https://github.com/mozilla-services/syncstorage-rs/issues/811
> Fix #811 Document use_test_transactions and expose it using an environment variable

- .circleci/config.yml
Dockerflow automation expects a version.json file
Deploy new image via automation
> bugfix: the python spanner utils image needs a version.json

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
*   Add quota monitoring (#806) ([9e6759e](https://github.com/mozilla-services/syncstorage-rs/commit/9e6759efef8f163355ee1b23dc28b716335df66d), closes [#791](https://github.com/mozilla-services/syncstorage-rs/issues/791), [#793](https://github.com/mozilla-services/syncstorage-rs/issues/793), [#797](https://github.com/mozilla-services/syncstorage-rs/issues/797), [#789](https://github.com/mozilla-services/syncstorage-rs/issues/789), [#801](https://github.com/mozilla-services/syncstorage-rs/issues/801))
*   Convert some of the validation storage errors into metrics (#810) ([66221d8b](https://github.com/mozilla-services/syncstorage-rs/commit/66221d8bec17f6134dee1b9d9005f5cdbe8121d3), closes [#795](https://github.com/mozilla-services/syncstorage-rs/issues/795))
*   switch from `regex_contains` …
> chore: tag 0.6.0

- src/db/spanner/batch.rs
- src/settings.rs
Closes #829
Do not enforce quota on MySQL DB users, since quotas aren't really required there. 
Also safeguard the quota size check in the spanner `do_append_sync()`.
Tests included.
Closes #829.
> bug: Disable quota check for mysql/stand-alone servers

- src/db/error.rs
- src/error.rs
Closes #836
Return status 403 (weave error "14") for users that trigger the Quota limits.
Start a server with 
```
SYNC_LIMITS__MAX_QUOTA_LIMIT=10 SYNC_ENABLE_QUOTA=1  ...
```
you can then use a script similar to the one in `tools/examples/put.bash` (mind that the value of `SYNC_MASTER_SECRET` matches whatever you're using for the sync server). Since that script attempts to put more than 10 bytes* it should fail with the correct statuscode and body.
* this script may need to be run a second time if the database is empty.
Closes #836 .
> bug: return correct error code and value for OverQuota users

- README.md
On Debian, there is not `libmysqlclient` available since Stretch. Debian has fully migrated to MariaDB as replacement. There is a `libmariadb-dev` package, which ships `libmariadbclient.so`, but this is currently not accepted by the `migrations_macros` compilation step. A simple solution is the available compat package: https://packages.debian.org/libmariadb-dev-compat
`cd syncstorage-rs && cargo run` on any distro using the Debian APT repository from Stretch up.
> Add libmysqlclient dependency solution for Debian

- Cargo.lock
- Cargo.toml
- src/main.rs
0.20.x fails to emit any events (maybe a CurlHttpTransport issue?)
Ensure hitting the `/__error__` endpoint emits an event
Issue #846
> fix: downgrade sentry to 0.19

- src/db/tests/batch.rs
- src/db/transaction.rs
I just merged a PR and noticed failing builds due to a clippy error (guessing due to timing around today's stable rust release). Fixed.
Doublecheck I didn't do anything silly as I'm not really much of a Rustacean :)
You could also run `cargo clippy --all --all-targets --all-features -- -D warnings` (which is what's run in CI) in this branch to see no more errors. Vs in master; see errors.
Closes [#850](https://github.com/mozilla-services/syncstorage-rs/issues/850).
> fix: clippy error related to matches!

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
*   Return FORBIDDEN if a user's batch is Over Quota (#848) ([d24dcdb6](https://github.com/mozilla-services/syncstorage-rs/commit/d24dcdb6c1a23ea725322830b82a3f31a11c7a8b), closes [#852](https://github.com/mozilla-services/syncstorage-rs/issues/852))
*   clippy error related to matches! closes #850 ([06aed80f](https://github.com/mozilla-services/syncstorage-rs/commit/06aed80f004c355f280d25c9d508b28038adf0f2))
*   downgrade sentry to 0.19 (#849) ([0a175dde](https://github.com/mozilla-services/syncstorage-rs/commit/0a175dde049b4661d681be5398941f6a3136a142))
*   Update circleci to use docker auth (#855) ([dcb0a0b2](https://github.com/mozilla-services/syncstorage-rs/commit/dcb0a0b23c78b5f07c0a8f4c2d91f4f5895a7515), closes [#854](https://github.com/mozilla-services/syncstorage-rs/issues/854)) …
> chore: tag 0.7.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Tagging 0.7.1 for release tomorrow.
I ran into some wonkiness when running `clog`. Specifically ran `clog -C CHANGELOG.md -p` - it looks like it picked up everything that's not been made an official GH release since 0.6.0...so I went and manually added what's changed post [0.7.0](https://github.com/mozilla-services/syncstorage-rs/releases/tag/0.7.0). Double check, make sure I didn't miss anything?
N/A
> chore: tag 0.7.1

- src/db/mysql/batch.rs
- src/db/tests/batch.rs
Closes #827
Handle duplicate keys while appending items into batch_upload_items
Test included.
Closes #827
> bug: handle duplicate keys in batch_upload_items for mysql

- spanner_config.ini
- src/db/params.rs
- src/db/spanner/BATCH_COMMIT.txt
- src/db/spanner/batch.rs
- src/db/spanner/models.rs
- src/db/tests/db.rs
- src/web/handlers.rs
and document batch commit's mutations
also reduce MAX_TOTAL_RECORDS for quota write allowance
TODO: https://github.com/mozilla-services/server-syncstorage/issues/155
Closes #869
> fix: avoid extra quota related work in batch commit 

- src/web/handlers.rs
this is equivalent to a simpler post_bsos call: so do that instead of
incurring post_collection_batch's overhead
e2e tests executes this path a couple of times (and there's a specific test_batch_with_immediate_commit test for it)
Closes #876
> feat: optimize POST w/ ?batch=true&commit=true

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
*   handle duplicate keys in batch_upload_items for mysql (#873) ([2d6039f3](https://github.com/mozilla-services/syncstorage-rs/commit/2d6039f3e6b130a3a45c6c1815c1bcc25279d451), closes [#827](https://github.com/mozilla-services/syncstorage-rs/issues/827))
*   reduce MAX_TOTAL_RECORDS for quota write allowance ([bac2c51f](https://github.com/mozilla-services/syncstorage-rs/commit/bac2c51f4f44289d982c69437b5e803948a6a1b7))
*   avoid extra quota related work in batch commit ([51c3bdab](https://github.com/mozilla-services/syncstorage-rs/commit/51c3bdab9988dcbfa59d10af5cda81335f71a270), closes [#869](https://github.com/mozilla-services/syncstorage-rs/issues/869))
*   correct quota env var in config test to SYNC_ENABLE_QUOTA (#859) ([f0aa4642](https://github.com/mozilla-services/syncstorage-rs/co …
> chore: tag 0.8.0

- Cargo.lock
- Cargo.toml
- src/db/mysql/models.rs
- src/db/mysql/test.rs
- src/db/tests/batch.rs
- src/error.rs
- src/server/test.rs
- src/web/extractors.rs
- src/web/handlers.rs
* cargo audit flagged a deep dependency,
* which required updating libraries
* which broke a few tests due to formatting
* which also required a few function changes due to obsolete
do CI tests pass and does the tree go green? 
👍 👍
> chore: update dependencies

- Cargo.lock
- Cargo.toml
redo of 0a175dde049 (this time with a comment)
syncstorage-local sentry works
Closes #907
> fix: downgrade to sentry 0.19

- src/error.rs
- src/server/metrics.rs
- src/server/mod.rs
- src/web/extractors.rs
- src/web/handlers.rs
- src/web/middleware/mod.rs
- src/web/tokenserver.rs
* adds dbg!()
* adds route for `/1.0/sync/1.5/{uid}` (not sure if that's needed.
> Tokenserver jr

- src/db/mysql/test.rs
- src/db/spanner/models.rs
- src/server/test.rs
- make server test uids random to avoid potential conflicts
- remove an extra check_quota call from test's spanner put_bso
This was actually a pain to do for another reason: these server tests don't persist the db across each request (they use `database_use_test_transactions`). That's easily fixed on a per test basis but then test failures can cause stale data to hang around, conflicting with other tests. Hence randomizing the uids.
new test passes
Closes #120
> test: add a basic overquota test

- src/server/test.rs
not ideal but a test w/ multiple write calls needs to handle 503s (similar to
the e2e test's retry delay)
tests should reliably pass on ci
Closes #920
> fix: add a short delay to avoid 503s

- .gitignore
- .sentryclirc.example
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- scripts/sentry-release.sh
Tagged 0.8.1 for release. Since I was planning to integrate sentry releases into this process I did that at the same time. If folks prefer to split that out separately from release tag, let me know I'll open a separate PR.
Note the newly added instructions to the README for creating sentry releases; make sense? Do they work for you?
Closes [#910](https://github.com/mozilla-services/syncstorage-rs/issues/910).
> Release/0.8.1 - and include details/helper script for creating sentry releases

- Cargo.lock
- Cargo.toml
- vendor/mozilla-rust-sdk/googleapis-raw/src/lib.rs
Update pyo3 to 0.12.4 due to a vulnerability in the yanked version 0.12.3. We were always on 0.12.1 before so were not affected.
Stuff should still work.
> Update pyo3 to the latest version.

- src/db/mysql/batch.rs
- src/db/results.rs
- src/db/spanner/batch.rs
- src/db/tests/batch.rs
- src/web/extractors.rs
- src/web/handlers.rs
- simplify results::CommitBatch
- kill the request.error.invalid_json metric (dupe of
request.validate.invalid_body_json)
mostly a refactor
Closes #933
Issue #835
> fix: prefer a set vs vec for the bso_id dupe check

- .circleci/config.yml
- Dockerfile
- docker-compose.e2e.yaml
- src/server/metrics.rs
- tests.ini
- tools/integration_tests/requirements.txt
- tools/integration_tests/run.py
- tools/integration_tests/test_storage.py
- tools/integration_tests/test_support.py
- tools/integration_tests/tests-no-batch.ini
- tools/integration_tests/tests-paginated.ini
- tools/integration_tests/tests.ini
Convert the integration tests to python 3, and run them in the same docker container as the rust server, hopefully greatly speeding up the build process. Converting the tests to python 3 is good because it is getting harder to acquire the python 2 compatible dependencies, and we finally need to change the tests to fix an id ordering bug.
The tests should continue passing.
Closes #911
> Py3 integration tests

- src/web/extractors.rs
- src/web/handlers.rs
Closes #947
Adds `quota` info to the `__heartbeat__` result.
Set quota via env vars like:
```
SYNC_ENABLE_QUOTA=true \
SYNC_ENFORCE_QUOTA=true \
SYNC_LIMITS__MAX_QUOTA_LIMIT=10000 \
... \
cargo run 
```
Verify that 
```
> curl http://localhost:8000/__heartbeat__
{"quota":{"enabled":true,"size":10000},"status":"Ok","version":"0.8.3","database":"Ok"}
```
If quota is not enabled, `__heartbeat__` should return something like:
```
> curl http://localhost:8000/__heartbeat__
{"version":"0.8.2","database":"Ok","quota":{"enabled":false,"size":2097152000},"status":"Ok"}
```
(The only field that matters here is `enabled`.)
Closes #947.
> feat: Add quota info to __heartbeat__

- src/db/mysql/pool.rs
- src/db/spanner/pool.rs
- src/settings.rs
and add a database_pool_connection_timout setting for it
On prod (#945)
Closes #973
> feat: default to timing out deadpool checkouts (30 seconds)

- Cargo.lock
- Cargo.toml
- src/settings.rs
needed for its timer usage (when enabling connection timeouts)
and set a default connection timeout
Tests now pass when using a connection timeout (which is now always enabled)
Closes #977, #976
> fix: downgrade deadpool so it stays on tokio 0.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/server/mod.rs
- src/server/test.rs
- src/settings.rs
- src/web/extractors.rs
- src/web/handlers.rs
This will add several fields to `__lbheartbeat__` if
`database_pool_max_size` is specified. These include:
```json
{
"active_connections": ... /* Number of active connections */,
"idle_connections": ... /* number of idle connections */,
"duration": ... /* how long no idle connections have been availble */,
}
```
Note that "duration" will only be present if `idle_connections` has been
zero since the last time a check was performed.
* this also adds `database_pool_max_size` as a config option.
`curl http://{server}/__lbheartbeat` should return 
200  with a body of
`{"active_connections":0,"idle_connections":0}`
(values may differ depending on the server being queried.
A saturated server should return something like:
`{"active_connections":0,"idle_connections":0, "duration_ms": 1000}` …
> feat: Add pool connection info to __lbheartbeat__ for ops

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Tagging for @Micheletto 
*   remove duplicate code for incrementing counters (#983) ([d72228b1](https://github.com/mozilla-services/syncstorage-rs/commit/d72228b1d4b5
cd63a399bde77c3156ea53bb4217))
*   tag 0.8.5 (#979) ([3c23fb46](https://github.com/mozilla-services/syncstorage-rs/commit/3c23fb46138d4a042d0293af6b9853ea9f173f6d))
*   Add pool connection info to __lbheartbeat__ for ops (#985) ([06a2ac79](https://github.com/mozilla-services/syncstorage-rs/commit/06a2ac79
10a87a75f1a2f0d68e786579cec99fd8))
*   downgrade deadpool so it stays on tokio 0.2 ([99975ef8](https://github.com/mozilla-services/syncstorage-rs/commit/99975ef8b64317511111d48
c6ebfc75e7facc334), closes [#976](https://github.com/mozilla-services/syncstorage-rs/issues/976))
> chore: tag 0.8.6

- src/server/test.rs
- src/web/handlers.rs
Closes #996
Return a 500 error if the connection pool is exhausted
Includes unit test
Closes #996
> feat: `__lbheartbeat__` will return 500 if the connection pool is exhausted

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
*   `__lbheartbeat__` will return 500 if the connection pool is exhausted (#997) ([e72573ac](https://github.com/mozilla-services/syncstorage-
rs/commit/e72573acedce2916c9fd3aa8e3c54fbe71f2008e), closes [#996](https://github.com/mozilla-services/syncstorage-rs/issues/996))
*   tag 0.8.6 (#995) ([8cb5b603](https://github.com/mozilla-services/syncstorage-rs/commit/8cb5b603f0320483904107eee682797b8d814a44))
> chore: tag 0.8.7

- Cargo.lock
- Cargo.toml
Closes #999
Include updated hyper 
N/A (internal build requirement)
Closes #999.
> chore: RUSTSEC-2021-0020 fix

- tools/integration_tests/test_storage.py
- tools/integration_tests/test_support.py
Make sure that the "extra" data passed to `
Code added to testing routines. 
Closes #1002.
> bug: ensure "extra" data added to Hawk header in e2e tests

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/web/handlers.rs
- tools/integration_tests/test_storage.py
The client may sometimes include bsos in the batch
commit message. The problem is that due to the way
that data is written to spanner, mutations do not
retain the ability to see data previously written
in the same transaction. This causes collisions.
To solve this, treat the bsos included in the commit
as another batch update, then commit all the data.
This does run the risk of bumping up against the
mutation limit, but it ensures the best chance of
data consistency.
Writing the commit bsos prior to batch commit will
result in the "newer" records being overwritten by
"older" ones in the batch.
Writing the commit bsos after the batch commit runs
the same mutation index conflict problem.
Unit test included
Closes #882
>  bug: write bsos contained within a commit after the batch has been commited.

- spanner_config.ini
- src/db/spanner/BATCH_COMMIT.txt
Adds documentation and comment requiring notification of the iOS team to change their hard coded values whenever we alter a limit.
documentation
Closes #1026.
> doc: Add reminders to notify iOS team on changing limits

- src/db/mysql/batch.rs
- src/db/mysql/models.rs
- src/db/spanner/batch.rs
- src/db/transaction.rs
- src/server/test.rs
- src/web/extractors.rs
- src/web/middleware/rejectua.rs
- src/web/middleware/sentry.rs
- src/web/tags.rs
This is not a resolution. Instead, this will report the query parameters
that lead to a serde parse failure so we can better isolate potential
problems.
(also fixes a typo in a logging message extra parameter)
Invalid values in query params that trigger serde parse errors should result in sentry messages containing the query parameters
Issue #1029
> bug: report query parameters with Invalid Value error

- tools/spanner/purge_ttl.py
Closes: #1034
adds `--auto_split` / `PURGE_AUTO_SPLIT` arg to auto-gen `uid_prefix` fields for _N_ digits, (e.g. `--auto_split=3` will generate prefixes of `["000","001","002",...,"fff"]`
You can use `--dry_run` and verify that queries for each prefix are generated
Closes #1034.
> feat: Add "auto-split" arg to auto-gen UID prefixes

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
*   Restore hawk error metrics (#1033) ([f795eb08](https://github.com/mozilla-services/syncstorage-rs/commit/f795eb0813b4ee37463add5391c829c906fdb35d), closes [#812](https://github.com/mozilla-services/syncstorage-rs/issues/812))
*   report query parameters with Invalid Value error (#1030) ([354cf794](https://github.com/mozilla-services/syncstorage-rs/commit/354cf794c59266dccfd3c6d12b880b466efa5650))
*   Add "auto-split" arg to auto-gen UID prefixes (#1035) ([487ac11e](https://github.com/mozilla-services/syncstorage-rs/commit/487ac11ed0abf4ddc77cea1be852169846796a57))
> chore: tag 0.10.0

- src/web/middleware/sentry.rs
`DbMiddleware` was removed in #693, and it was the last piece of code that referenced the `middleware::sentry::queue_report` function; this PR removes the function.
N/A
Closes #1021
> refactor: Remove middleware::sentry::queue_report

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* This minor tag caches changes to `purge_ttl.py` that were missed by 0.10.0
*   Remove middleware::sentry::queue_report (#1040) ([0dccb00f](https://github.com/mozilla-services/syncstorage-rs/commit/0dccb00fb95d0aebabe79d5e6ecb1fb537445444))
> chore: tag 0.10.1

- src/web/extractors.rs
Refactors parts of the web extractors to use a generic tuple extractor pattern in Rust. There was some discussion in #698 as to which of the two variants is more performant:
Generic tuple extraction:
```rust
let (user_id, query, collection, bso, body) =
<(
HawkIdentifier,
BsoQueryParams,
CollectionParam,
BsoParam,
BsoBody,
)>::from_request(&req, &mut payload)
.await?;
```
Extracting the values separately:
```rust
let user_id = HawkIdentifier::from_request(&req, &mut payload).await?;
let collection = CollectionParam::from_request(&req, &mut payload).await?;
let query = BsoQueryParams::from_request(&req, &mut payload).await?;
let bso = BsoParam::from_request(&req, &mut payload).await?;
let body = BsoBody::from_request(&req, &mut payload).await?;
```
The idea is that in the second example …
> refactor: Use generic tuple extractor in web extractors

- src/error.rs
- src/web/error.rs
- src/web/extractors.rs
* removes extra metric call
* fixes up label to match existing metrics
Various validation errors (Like an invalid content type for a BSO) should not be sent to Sentry, but should instead increment an appropriate metric (e.g. `syncstorage.request.validate.invalid_content_type`)
Closes #1037.
> fix: use ValidationErrorKind metric_label in ApiError 

- src/db/spanner/batch.rs
- src/db/spanner/macros.rs
- src/db/spanner/models.rs
- src/db/spanner/support.rs
Improves our conversion of `String`s, `i32`s, and `u32`s to protobuf `Value`s by using a `ToSpannerValue` trait. This makes adding support for the conversion of a new type to a `Value` as easy as adding a `ToSpannerValue` implementation for that type.
I tested this using the integration tests in `tools/integration_tests/`. To do this, I:
- Changed [this line](https://github.com/mozilla-services/syncstorage-rs/blob/master/tools/integration_tests/run.py#L25) to read:
```python
the_server_subprocess = subprocess.Popen('SYNC_MASTER_SECRET=secret0 ' + target_binary + ' --config ./config/local.toml', shell=True)
```
- Ran `python3 tools/integration_tests/run.py 'http://localhost:8000#secret0'`
There was one integration test failure:
``` …
```
> refactor: Add ToSpannerValue trait

- Cargo.lock
- Cargo.toml
- src/web/tokenserver.rs
Replaces the inlined Python code with native Rust code. I replaced all of the Python functions with equivalent Rust functions, except for `tokenlib#make_token` and `tokenlib#get_derived_secret`, which I added Rust wrappers for.
I tested this by running the Python and Rust versions with the same input data and ensuring that the output was the same.
Python test file: https://gist.github.com/ethowitz/7d6b3590f4aae0c51b2df71297c1d303
Rust test code (I added this to syncstorage-rs's main function for expediency): https://gist.github.com/ethowitz/2ec06b230b2db66de6088ac30a8c9819
Python output:
```
dGVzdGluZzEyMw # URL-safe base64 encoded string with stripped padding
51c982a4554222dce10f7fd77145a92f87a6f55934403ff8d2546d6c0a4da872 # FxA metrics hash
402e41f93a922d7517f43668d2392e72 # hashed …
```
> refactor: Tokenserver: Rewrite inlined Python code in Rust

- Cargo.toml
we're blocked from updating to the latest deadpool (due to its tokio 1.0 usage,
blocked on actix-web 4) so bring in our fork of the older deadpool-v0.5.2 for
now
stage/prod idle connection metrics should stop unbounded growth over time
Closes #803
NOTE: merging to a release/0.10 branch
> fix: update deadpool w/ the incorrect pool stats fix

- src/db/spanner/batch.rs
- src/db/spanner/macros.rs
- src/db/spanner/models.rs
- src/db/spanner/support.rs
In the `ToSpannerValue` implementations for `i32` and `u32`, we were using `Value::set_number_value()` to construct a `Value` from an integer. In doing so, we coerced the integers into floats, which is what created the errors on Spanner. To resolve this, I convert the integral values to strings prior to creating a `Value`.
The issue can be reproduced on the main branch by adding a new bookmark and syncing (your local server should throw the [same error that appeared in Sentry](https://sentry.prod.mozaws.net/operations/syncstorage-dev/issues/11102490/?query=is%3Aunresolved). Switching to this feature branch, adding a new bookmark, (recompiling,) and syncing should result in a successful sync, with no errors reported.
Closes #1055
> fix: Convert integral values to String before converting to Value

- src/db/spanner/manager/deadpool.rs
- src/db/spanner/manager/session.rs
- src/settings.rs
Adds support for a `SYNC_SPANNER_EMULATOR_HOST` environment variable. When the environment variable is set, the session manager will attempt to create an insecure gRPC channel to the Spanner instance running at that host. If it is not set, it will create a secure connection to the default Spanner instance as it previously did.
I was able to test this by adding `println!`s in `session::create_spanner_session()` like so:
```rust
pub async fn create_spanner_session(
env: Arc<Environment>,
mut metrics: Metrics,
database_name: &str,
use_test_transactions: bool,
emulator_host: Option<String>,
) -> Result<SpannerSession, DbError> {
// XXX: issue732: Could google_default_credentials (or
// ChannelBuilder::secure_connect) block?!
let chan = block(move || -> Result<grpcio::Channel, grpcio::Error> { …
```
> feat: Support SYNC_SPANNER_EMULATOR_HOST

- Makefile
- README.md
Updates the documentation to include the following information:
- How to install the `gcloud` CLI tool
- How to authenticate using `gcloud auth application-default login` to generate a JSON file with an OAuth token in the proper location
- How to symlink this file to be picked up by `.gitignore`
- How to revoke these credentials in case of a leak
A question for the reviewer: is it worth including the URL that points to the Spanner instance that should be used for development?
I tested this by revoking my previous OAuth keys, running through the new workflow outlined in the docs, and ensuring that I was able to access the Spanner dev instance with the newly-generated credentials.
Closes #1045
> docs: Update spanner configuration documentation

- src/db/spanner/manager/session.rs
- src/db/spanner/models.rs
- src/db/spanner/support.rs
- src/db/tests/db.rs
- src/web/extractors.rs
- src/web/middleware/rejectua.rs
These changes fix build errors caused by the new Rust version.
These changes are trivial -- in each case, I used Clippy's suggested fix. If the tests pass and the build succeeds, the changes should be sound.
Closes #1105
> bug: Fix build for Rust 1.53.0

- scripts/prepare-spanner.sh
Adds an Apache 2.0 license to `prepare-spanner.sh`. The file from which `prepare-spanner.sh` was derived is here: https://github.com/cloudspannerecosystem/emulator-samples/blob/master/docker/start_emulator_with_instance_and_database.sh
N/A
N/A
> docs: Add Apache 2.0 license to prepare-spanner.sh

- src/bin/purge_ttl.rs
- src/db/mod.rs
- src/db/mysql/models.rs
- src/db/mysql/test.rs
- src/db/spanner/models.rs
- src/db/spanner/support.rs
- src/db/transaction.rs
- src/main.rs
- src/server/metrics.rs
- src/server/test.rs
- src/server/user_agent.rs
- src/tokenserver/support.rs
- src/web/auth.rs
- src/web/extractors.rs
- src/web/middleware/mod.rs
- src/web/tags.rs
Updates the code to conform to Rust 1.54.0
N/A
N/A
> chore: Update code for Rust 1.54.0

- .circleci/config.yml
- Makefile
- docker-compose.e2e.mysql.yaml
- docker-compose.e2e.spanner.yaml
- docker-compose.mysql.yaml
- docker-compose.spanner.yaml
- src/db/mysql/mod.rs
- src/db/mysql/models.rs
- src/db/mysql/pool.rs
- src/server/mod.rs
- src/server/test.rs
- src/settings.rs
- src/tokenserver/db/mock.rs
- src/tokenserver/db/mod.rs
- src/tokenserver/db/models.rs
- src/tokenserver/db/params.rs
- src/tokenserver/db/pool.rs
- src/tokenserver/db/results.rs
- src/tokenserver/extractors.rs
- src/tokenserver/handlers.rs
- src/tokenserver/migrations/2021-07-16-001122_init/down.sql
- src/tokenserver/migrations/2021-07-16-001122_init/up.sql
- src/tokenserver/mod.rs
- src/tokenserver/settings.rs
- src/tokenserver/support.rs
- src/web/extractors.rs
Adds mature infrastructure for a Tokenserver-specific MySQL database.
* Create an account on FxA stage: https://accounts.stage.mozaws.net/signup
* Set `identity.fxaccounts.remote.oauth.uri` to https://oauth.stage.mozaws.net
* Set `identity.fxaccounts.remote.root` to https://accounts.stage.mozaws.net
* Set `identity.fxaccounts.auth.uri` to https://api-accounts.stage.mozaws.net/v1
* Set `identity.fxaccounts.remote.profile.uri` to https://profile.stage.mozaws.net/v1
* Set `identity.sync.tokenserver.uri` to http://localhost:8000/1.0/sync/1.5
* Create a Tokenserver database:
```sql
CREATE DATABASE tokenserver_rs;
```
* Add a service and a node to your database:
```sql
INSERT INTO services (service) VALUES("sync-1.5");
INSERT INTO nodes (service, node, available, capacity) VALUES([service ID …
```
> refactor: Tokenserver: Add mature MySQL adapter

- .circleci/config.yml
- Cargo.lock
- Cargo.toml
- src/main.rs
update sentry version and remove ignore rustsec-2020-0041 in circle config, some code changes based on changes between sentry versions
rustsec-2020-0041 should no longer show up when you `cargo audit`
Closes #1024.
> update sentry ver and remove ignore rustsec-2020-0041 in circle config

- src/server/mod.rs
- src/tokenserver/db/mock.rs
- src/tokenserver/db/mod.rs
- src/tokenserver/db/models.rs
- src/tokenserver/db/params.rs
- src/tokenserver/db/results.rs
- src/tokenserver/extractors.rs
- src/tokenserver/handlers.rs
- src/tokenserver/migrations/2021-08-03-234845_populate_services/down.sql
- src/tokenserver/migrations/2021-08-03-234845_populate_services/up.sql
- src/tokenserver/support.rs
Adds the relevant database methods necessary to implement the consistency checks between `generation`, `keys_changed_at`, and `client_state` and update the user, implemented [here](https://github.com/mozilla-services/tokenserver/blob/master/tokenserver/views.py#L403) in the legacy Tokenserver.
These methods are not actually used yet, so there's no way to test externally. The unit tests should suffice for now, until we can properly end-to-end test after #866 and #1133 are completed.
Closes #1132
> feat: generation, keys_changed_at, and client_state: Add database methods

- Cargo.lock
- Cargo.toml
RUSTSEC-2021-0081 appeared due to current version of actix-http being 2.2.0. 
RUSTSEC-2021-0081 should not be appearing in `cargo audit`
> chore: update actix-http version due to RUSTSEC-2021-0081

- Cargo.toml
- src/tokenserver/error.rs
- src/tokenserver/extractors.rs
- src/tokenserver/mod.rs
- src/tokenserver/support.rs
* Implements a number of extractors to support adding validations in #866 
* Adds `TokenserverError` and `Serialize` `impl`s to support errors formatted the same as the errors on the legacy Tokenserver
The unit tests cover the error cases pretty comprehensively, but to test end-to-end:
* Create an account on FxA stage: https://accounts.stage.mozaws.net/signup
* Set `identity.fxaccounts.remote.oauth.uri` to https://oauth.stage.mozaws.net
* Set `identity.fxaccounts.remote.root` to https://accounts.stage.mozaws.net
* Set `identity.fxaccounts.auth.uri` to https://api-accounts.stage.mozaws.net/v1
* Set `identity.fxaccounts.remote.profile.uri` to https://profile.stage.mozaws.net/v1
* Set `identity.sync.tokenserver.uri` to http://localhost:8000/1.0/sync/1.5
* Create a Tokenserver database: …
> feat: Tokenserver: Implement extractors for generation, keys_changed_at, client_state

- Cargo.lock
- Cargo.toml
- src/settings.rs
- src/tokenserver/mod.rs
- src/tokenserver/settings.rs
- src/tokenserver/support.rs
Adds a "test mode" to Tokenserver, which extracts information from JWT OAuth tokens without cryptographically verifying them.
* Uncomment lines 143-146 in [src/server/mod.rs](https://github.com/mozilla-services/syncstorage-rs/blob/e6e2bbda3bde8f125729f237be27392835ce22c5/src/server/mod.rs#L143)
* Add `println!("{:?}", token_data);` to line 41 of [src/tokenserver/extractors.rs](https://github.com/mozilla-services/syncstorage-rs/blob/e6e2bbda3bde8f125729f237be27392835ce22c5/src/tokenserver/extractors.rs#L41)
* Add `tokenserver.test_mode_enabled = true` to `local.toml`
* Run the server with `make run`
* Send a request with a Tokenserver OAuth token (e.g. using HTTPie, `http GET localhost:8000/1.0/sync/1.5 'Authorization:Bearer <your token here>'`)
* Verify that the data extracted from the …
> feat: Add test mode to Tokenserver

- src/tokenserver/extractors.rs
- src/tokenserver/handlers.rs
Setting the `duration` query parameter adjusts the expiry time of the token returned by Tokenserver. If the query parameter cannot be parsed or if the query parameter is greater than the default token duration set on the server, the default token duration is used instead.
This can be tested by sending requests to Tokenserver using HTTPie like so:
```bash
http GET localhost:8000/1.0/sync/1.5 'Authorization:Bearer <insert JWT here>' 'X-KeyID:<insert kid here>' duration==100
```
You can inspect the 'duration' field of the JSON returned by the endpoint to ensure its value matches your expectations.
Closes #1050
> feat: Tokenserver: Add support for client-specified token duration

- src/db/error.rs
- src/tokenserver/db/mock.rs
- src/tokenserver/db/models.rs
- src/tokenserver/db/params.rs
- src/tokenserver/db/results.rs
- src/tokenserver/error.rs
- src/tokenserver/extractors.rs
- src/tokenserver/handlers.rs
- src/tokenserver/mod.rs
- src/tokenserver/settings.rs
- tools/integration_tests/tokenserver/test_misc.py
Adds the logic used to create users and assign them to the correct nodes.
I added integration and unit tests that provide comprehensive coverage, but the following cases are the important ones:
- Users are always allocated to the least-loaded node
- When a user is allocated to a node, `available` and `current_load` are adjusted accordingly
- When no nodes have capacity, Tokenserver attempts to release capacity on nodes where `available` is zero but `current_load` is less than `capacity`
Closes #1051
> feat: Tokenserver: Add node assignment logic

- src/tokenserver/extractors.rs
Adds a few comments to explain why we need to temporarily call `unwrap()` on `tokenserver_state`.
N/A
Closes #1102
> docs: Add comments about `tokenserver_state` being an `Option`

- src/tokenserver/extractors.rs
- tools/integration_tests/tokenserver/test_authorization.py
* Validates that the `X-Client-State` header (if present) is of the correct format
* Fixes the format of the error we're returning if the client state in `X-KeyID` is of the incorrect format
I added a new integration test to address the new `X-Client-State` validation. You can verify that it passes against both the old and the new Tokenserver.
Closes #1091
> feat: Add client state validation

- src/tokenserver/db/mock.rs
- src/tokenserver/db/models.rs
- src/tokenserver/db/pool.rs
- src/tokenserver/extractors.rs
- src/web/handlers.rs
Makes the `DbPool#get` method async
This change should be transparent; no functionality was changed.
Closes #1172
> feat: make Tokenserver DbPool#get async

- .circleci/config.yml
- src/tokenserver/handlers.rs
- src/tokenserver/secrets.py
- src/tokenserver/support.rs
- tools/integration_tests/tokenserver/test_e2e.py
- tools/integration_tests/tokenserver/test_support.py
Instead of using a single secret for every node, this PR introduces a change such that a different secret is derived for each node.
I updated an integration test to match the code change. You can verify that the test passes against both the legacy and new Tokenservers. (Note that the last two assertions of the test will fail on the new Tokenserver due to missing fields on the response (to be fixed in another PR), but the assertion having to do with the derived secret passes.)
Closes #1104
> feat: Tokenserver: add per-node secrets

- src/settings.rs
- src/tokenserver/extractors.rs
- src/tokenserver/handlers.rs
- src/tokenserver/mod.rs
- src/tokenserver/settings.rs
- tools/integration_tests/tokenserver/test_e2e.py
Adds `hashalg` and `node_type` to the Tokenserver response.
Sending a request to Tokenserver will yield a response with the two added fields. Alternatively, the end-to-end integration tests test that these fields are present.
Closes #1173
> feat: add missing Tokenserver response fields

- .circleci/config.yml
- Cargo.toml
- Dockerfile
- Makefile
- docker-compose.e2e.mysql.yaml
- docker-compose.e2e.spanner.yaml
- docker-compose.mysql.yaml
- requirements.txt
- src/server/mod.rs
- src/tokenserver/mod.rs
- tools/integration_tests/requirements.txt
- tools/integration_tests/run.py
- tools/integration_tests/tokenserver/test_e2e.py
- tools/integration_tests/tokenserver/test_support.py
Makes the changes necessary to run the Tokenserver integration tests in CI.
N/A
Closes #1174
> test: add Tokenserver integration tests to CI

- src/tokenserver/db/pool.rs
- src/tokenserver/extractors.rs
- tools/tokenserver/loadtests/README.md
- tools/tokenserver/loadtests/locustfile.py
- tools/tokenserver/loadtests/mock-oauth-cfn.yaml
- tools/tokenserver/loadtests/populate_db.py
- tools/tokenserver/loadtests/requirements.txt
Adds a suite of locust load tests for Tokenserver.
The load test suite currently doesn't run well against the new Tokenserver (I think there is an issue without how I configured the database; I'll look into this separately). Running it against the old Tokenserver should work without issue (you'll need to configure the old Tokenserver to verify OAuth tokens through the mock service at https://mock-oauth-stage.dev.lcip.org).
Closes #1107
> test: add Tokenserver load tests

- Makefile
- src/tokenserver/db/mock.rs
- src/tokenserver/db/models.rs
- src/tokenserver/db/params.rs
- src/tokenserver/db/pool.rs
- src/tokenserver/db/results.rs
- src/tokenserver/error.rs
- src/tokenserver/extractors.rs
Moves blocking I/O method calls to the blocking threadpool.
Running the load test suite against Tokenserver with 100 users should result in no errors.
Closes #1188
> fix: move I/O calls to blocking threadpool

- .cargo/audit.toml
- .circleci/config.yml
- src/tokenserver/db/mock.rs
- src/tokenserver/db/mod.rs
- src/tokenserver/db/models.rs
- src/tokenserver/db/params.rs
- src/tokenserver/db/pool.rs
- src/tokenserver/db/results.rs
- src/tokenserver/extractors.rs
- src/tokenserver/migrations/2021-12-22-160451_remove_services/down.sql
- src/tokenserver/migrations/2021-12-22-160451_remove_services/up.sql
- src/tokenserver/mod.rs
- tools/integration_tests/tokenserver/test_misc.py
- tools/integration_tests/tokenserver/test_node_assignment.py
- tools/integration_tests/tokenserver/test_support.py
- tools/tokenserver/database.py
- tools/tokenserver/test_database.py
- tools/tokenserver/test_process_account_events.py
- tools/tokenserver/test_purge_old_records.py
- tools/tokenserver/test_scripts.py
Removes the two statically-defined services from the database via a new migration. Makes updates to the application code and integration tests to reflect the change in schema.
Passing unit and integration tests should sufficiently show that the change was successful.
Closes #1144
> refactor: remove static service IDs

- src/server/metrics.rs
- src/tokenserver/extractors.rs
- src/tokenserver/mod.rs
Adds a `TokenserverMetrics` wrapper type to allow for a Tokenserver-specific `FromRequest` impl for `Metrics` (the existing impl doesn't work because it looks for the `Metrics` object in the syncstorage `ServerState` instead of the Tokenserver `ServerState`
I tested this by running Tokenserver, sending a request, and ensuring that the "metric error: No App State" error message was no longer being logged.
Closes #1214
> bug: fix Tokenserver metrics

- src/server/mod.rs
- src/tokenserver/handlers.rs
- tools/integration_tests/tokenserver/test_e2e.py
Adds the missing `X-Timestamp` to responses from Tokenserver. The python equivalent can be found [here](https://github.com/mozilla-services/tokenserver/blob/master/tokenserver%2Ftweens.py#L13). I also double-checked the response from the Python Tokenserver to ensure there weren't any other missing headers that should be added here.
I added new integration tests to check for the new headers.
Closes #1242
> bug: add missing Tokenserver headers

- src/server/metrics.rs
- src/server/mod.rs
- src/server/test.rs
- src/tokenserver/auth/mod.rs
- src/tokenserver/handlers.rs
- src/web/auth.rs
- src/web/extractors.rs
- src/web/handlers.rs
- src/web/middleware/mod.rs
- src/web/tags.rs
- tools/integration_tests/tokenserver/test_e2e.py
* Add a new `tokenserver_origin` field to the `HawkPayload` so syncstorage can determine which tokens originated from
* Parse the field on the syncstorage side and add it as a tag to some key metrics
* Add the Tokenserver origin as a tag on the HTTP status and API metrics
I wasn't sure how to test that the metrics were being emitted properly, but I added an integration test to ensure that the field is present in the token created by Tokenserver.
Closes #1245
> feat: pass Tokenserver origin field through token payload

- src/tokenserver/migrations/2021-07-16-001122_init/up.sql
- src/tokenserver/migrations/2021-08-03-234845_populate_services/up.sql
- src/tokenserver/migrations/2021-12-22-160451_remove_services/down.sql
Migrations were previously failing in GCP because the `services` table
already exists in the database. To rectify this, we needed to change the
`CREATE TABLE` statements to `CREATE TABLE IF NOT EXISTS`. We also had
to change any `INSERT` statements to `INSERT IGNORE` statements.
I tested this by reverting all the migrations, manually adding the tables and `sync-1.1` and `sync-1.5` services, and running the migrations. The migrations should complete with no errors.
> bug: fix Tokenserver migrations

- .circleci/config.yml
per https://github.com/mozilla-services/Dockerflow/pull/44
_TAG seems to only fix this issue on tagged builds, whereas _SHA1 should also
solve it on dev builds lacking a tag
Closes #1284
> chore: prefer CIRCLE_SHA1 vs CIRCLE_TAG in circle's cache key

- Makefile
- docker-compose.e2e.mysql.yaml
- docker-compose.e2e.spanner.yaml
- docker-compose.mysql.yaml
- docker-compose.spanner.yaml
- src/settings.rs
- src/tokenserver/README.md
- src/tokenserver/db/pool.rs
- src/tokenserver/settings.rs
Since we're connecting to the pre-existing Tokenserver database, we should not be running the migrations on server startup.
> feat: don't run Tokenserver migrations on startup

- .cargo/audit.toml
- Cargo.lock
- Dockerfile
(#1215 follow up) we shouldn't need it enabled since moving to reqwest+rustls
and upgrade the easier dependencies
Issue #1215
@ethowitz these Cargo.lock changes will conflict with your crate refactor branch but I think you can easily nuke the Cargo.lock there and let cargo rebuild it for the same effect. I just wanted to get some in now before tagging a new syncstorage release.
> chore: disable grpcio openssl

- src/tokenserver/auth/browserid.rs
- src/tokenserver/db/models.rs
- src/tokenserver/db/pool.rs
- src/tokenserver/extractors.rs
- src/tokenserver/handlers.rs
Three small changes:
* We were extracting the Tokenserver metrics reporter incorrectly, which I noticed when we weren't receiving one of the metrics correctly
* The Tokenserver statsd label already has `tokenserver.` in it, so remove that prefix from the places in the code where we emit metrics
* Add context to unrecognized BrowserID verification errors that have a reason message
> bug: fix metrics and BrowserID error context

- docker-compose.e2e.mysql.yaml
- docker-compose.e2e.spanner.yaml
- syncstorage/src/tokenserver/auth/oauth.rs
- syncstorage/src/tokenserver/auth/verify.py
- syncstorage/src/tokenserver/mod.rs
- syncstorage/src/tokenserver/settings.rs
The Python Tokenserver supports setting the JWK used to verify OAuth tokens, [which prevents the `PyFxA` library from having to make a request to FxA to verify tokens](https://github.com/mozilla/PyFxA/blob/main/fxa/oauth.py#L288). Eliminating this request will yield substantial performance benefits.
I tested this by adding a `print` statement in `verify.py` to ensure that the JWK was properly being passed into the pyfxa OAuth `Client`.
> feat: support setting JWK for Tokenserver OAuth verification

- .circleci/config.yml
Rust 1.61.0 uses substantially more memory than 1.60.0 in our CI builds, preventing them from completing (and preventing us from merging anything new). This PR pins Rust 1.60.0 until the issue is resolved upstream.
Upstream issue: https://github.com/rust-lang/rust/issues/97549
> chore: pin Rust 1.60.0

- .circleci/config.yml
- syncstorage/src/web/handlers.rs
Simple change to replace `dbg!` marco with the slog-rs `trace!` macro, since the `dbg!` was resulting in stderr output, not to stdout.
Compiles and matches patterns in rest of `handlers.rs` file.
Had to make alterations within the `.circleci` yaml file. @pjenvey was essential in identifying issue where cargo build pulls in most recent rust version which is often at odds with the specified version in the Docker build, which is explicitly hard-coded. 
Commented out commands to build rust and update which would override specified version in CI/CD. In the future, these lines can be commented back in and a `|` inserted at start of command directive.
Also, it was necessary to add the `no_output_timeout` directive to `cargo build` to allow for longer compilation times. …
> refactor: replaced dbg! with trace macro

- syncstorage/src/tokenserver/db/models.rs
- syncstorage/src/tokenserver/db/params.rs
- syncstorage/src/tokenserver/db/pool.rs
- syncstorage/src/tokenserver/extractors.rs
- syncstorage/src/tokenserver/handlers.rs
- syncstorage/src/tokenserver/mod.rs
A few more changes I wanted to make before we load test:
* Only call `Db::put_user` if there are changes that need to be made to the user record
* Remove an unnecessary call to `Db::get_node_id` when the Spanner node ID is cached
* Cache `spanner_node_id` and `service_id` on `TokenserverPool` and `TokenserverDb` instead of on `ServerState` (this isn't really a performance improvement; just a refactor I thought made sense given the changes here)
* Add metrics for some of the most common database methods
These changes should be transparent. The caching of the Spanner node ID already has test coverage, and user updates have integration test coverage.
> perf: remove unnecessary database calls for Tokenserver

- tools/tokenserver/loadtests/requirements.txt
`jwt` was specified as the JWT library to be used for the Tokenserver load tests, but `pyjwt` should have been used instead.
Closes #1372
> bug: fix JWT library for Tokenserver load tests

- .gitignore
- syncstorage/src/db/mod.rs
- syncstorage/src/db/mysql/pool.rs
- syncstorage/src/db/spanner/pool.rs
- syncstorage/src/server/test.rs
- syncstorage/src/settings.rs
- syncstorage/src/tokenserver/auth/oauth.rs
- syncstorage/src/tokenserver/db/pool.rs
- syncstorage/src/tokenserver/settings.rs
- syncstorage/src/web/auth.rs
- syncstorage/src/web/handlers.rs
In a previous commit, I refactored syncstorage-rs to use tokio's `task::spawn_blocking` to add blocking tasks to tokio's blocking threadpool. Since the tokio runtime is started up by Actix, we don't have easy control over the number of threads in the blocking threadpool. We should stick with using Actix's [`web::block`](https://docs.rs/actix-web/3.3.3/actix_web/web/fn.block.html) to spawn blocking tasks, since we can control the size of the blocking threadpool using `ACTIX_THREADPOOL`.
This PR switches back to using `web::block`. It also:
* Adds the ability for the server to correctly set `ACTIX_THREADPOOL` based on the sizes of the Syncstorage and Tokenserver database connection pools
* Adds an `additional_blocking_threads_for_fxa_requests` setting to add more blocking threads when the …
> feat: use Actix to spawn blocking threads

- Cargo.lock
- syncstorage-common/src/lib.rs
- syncstorage-db-common/src/error.rs
- syncstorage/src/error.rs
- syncstorage/src/server/mod.rs
- syncstorage/src/tokenserver/auth/browserid.rs
- syncstorage/src/tokenserver/handlers.rs
- syncstorage/src/web/middleware/sentry.rs
- tokenserver-common/Cargo.toml
- tokenserver-common/src/error.rs
* Add the `/__error__` Dockerflow endpoint to Tokenserver
* Report `TokenserverError`s to Sentry
The endpoint itself can be tested by running the server and sending `GET /__error__` to ensure that an error is correctly generated. I wasn't sure how to test integration with Sentry.
Closes #1364
> feat: add `__error__` endpoint to Tokenserver

- syncstorage/src/tokenserver/db/models.rs
A quick fix to the query that assigns a user to a node to match [the logic on the Python Tokenserver](https://github.com/mozilla-services/tokenserver/blob/master/tokenserver/assignment/sqlnode/sql.py#L748)
> bug: fix Tokenserver node assignment query

- syncstorage/src/tokenserver/db/models.rs
Fixes a query syntax error involving a stray comma at the end of a line.
I tested this by sending a request to my local Tokenserver and ensuring that the query ran without issue.
> bug: fix Tokenserver Spanner node query

- syncstorage/src/tokenserver/db/models.rs
- syncstorage/src/web/extractors.rs
* Add the Tokenserver origin as a Syncstorage extra to report along with Sentry errors
* Add a timer metric for the `add_users_to_node` query (every request to Tokenserver that results in a user allocation will result in a write to the Spanner node in the database, which has the potential to be a major bottleneck if we see a lot of new users concurrently)
I tested this by ensuring that new user allocations succeed without issue. I will test the new Sentry error tag on dev when this PR is merged.
> feat: add Tokenserver origin Sentry tag

- syncstorage/src/tokenserver/auth/oauth.rs
we have a `Result<VerifyOutput, BlockingError<TokenserverError>>` here. mapping all BlockingError::Error values to resource_unavailable causes 503 response for expired oauth tokens, which breaks sync from firefox. we previously returned the wrapped error unaltered (only turning a JoinError into resource_unavailable), so go back to that.
reliably: use 0.12.1 with an expired or revoked oauth token and observe that sync does not work and does not recover. apply patch and see it recover.
none.
> don't convert all oauth token verification errors to resource_unavailable

- syncstorage/src/settings.rs
- syncstorage/src/tokenserver/db/models.rs
- syncstorage/src/tokenserver/extractors.rs
- syncstorage/src/tokenserver/handlers.rs
- syncstorage/src/tokenserver/mod.rs
- syncstorage/src/tokenserver/settings.rs
- tools/integration_tests/tokenserver/test_authorization.py
- tools/integration_tests/tokenserver/test_browserid.py
- tools/integration_tests/tokenserver/test_e2e.py
- tools/integration_tests/tokenserver/test_misc.py
- tools/integration_tests/tokenserver/test_support.py
There were a few missing cases relating to how we handle generation and keys_changed_at:
* When Tokenserver gets an updated keys_changed_at in a request but that request has no generation and the generation on the user record is less than the new keys_changed_at, it should set the generation equal to the updated keys_changed_at
* Rust Tokenserver was setting the generation to be the keys_changed_at in the request even when the request didn't contain an updated keys_changed_at
* Once Tokenserver sees a client state and keys_changed_at for a user, it requires both of them in every request going forward (this is only relevant for BrowserID requests, since all OAuth requests must contain both keys_changed_at and client state in the form of an `X-KeyID` header
* Rust Tokenserver was allowing …
> bug: fix Tokenserver generation and keys_changed_at handling

- syncstorage/src/tokenserver/handlers.rs
- tools/integration_tests/tokenserver/test_misc.py
We had originally intended to set this header on nginx, but we don't use nginx for the Rust Tokenserver, and it turns out the method we _could_ use to set this header on the GCP load balancer is not persistent, so, I added it explicitly here. This header was set automatically on the Python Tokenserver by the Pyramid cornice library.
I added an integration test to ensure that the header is set, and I made sure that the integration test passes against the Python Tokenserver.
> feat: Add `X-Content-Type-Options: nosniff` to Tokenserver responses

- syncstorage/src/tokenserver/auth/oauth.rs
When an OAuth token being verified is not a JWT or the key being used to verify the signature is not a JWK, PyFxA falls back to verifying the token by making a request to FxA: https://github.com/mozilla/PyFxA/blob/main/fxa/oauth.py#L303
This means that, even if the JWK is cached, it's possible that a request will be dispatched, which would block the Actix worker from processing any other requests until that request returns. To account for this, we should always be verifying tokens with PyFxA in a thread on the blocking threadpool.
In practice, OAuth tokens being sent by Firefox clients should always be well-formed, but if a bad actor were to spam `GET /1.0/sync/1.5` with garbage in the `Authorization` header, it could block the worker threads and significantly affect performance for other …
> perf: always verify OAuth tokens on blocking thread

- tokenserver-settings/src/lib.rs
- tools/integration_tests/run.py
Runs the Tokenserver E2E integration tests against a Tokenserver without a cached FxA public JWK. This was done to ensure that we have test coverage for the OAuth verification code paths that involve making a request to FxA to verify tokens. We didn't have coverage before and it hid [a bug](https://github.com/mozilla-services/syncstorage-rs/pull/1389) where we were incorrectly handling `BlockingError`s returned by Actix's `web::block`.
I made sure that the `test_unauthorized_oauth_error_status` test failed without ebdd609 and passed with it
> test: run the Tokenserver E2E tests without a cached JWK

- .github/dependabot.yml
Let's plan to switch this back on when we're done with the crate reorg (and updating the deps afterwards)
> chore: temporarily disable dependabot

- syncserver/src/db/mysql/models.rs
- syncserver/src/db/spanner/batch.rs
- syncserver/src/db/spanner/models.rs
- syncserver/src/db/transaction.rs
- syncserver/src/server/metrics.rs
- syncserver/src/server/mod.rs
- syncserver/src/server/test.rs
- syncserver/src/tokenserver/extractors.rs
- syncserver/src/web/extractors.rs
- syncserver/src/web/handlers.rs
- syncserver/src/web/middleware/mod.rs
- syncserver/src/web/middleware/rejectua.rs
- syncserver/src/web/middleware/sentry.rs
- syncserver/src/web/tags.rs
The primary purpose of this change is to reduce the cardinality of the tags we're including with InfluxDB metrics by removing user agent data. I also wanted to make it more ergonomic to use (and more difficult to misuse) tags in general, so I made a few other improvements to our tagging code:
* Previously, there were several ways to construct a `Metrics` object, including ways that didn't involve deriving the object from the `HttpRequest`. This is bad because a `Metrics` that isn't derived from `HttpRequest` won't include any tags that were persisted to the request extensions. I removed the trait implementations and functions that enabled this; `FromRequest` is now the only way to construct a `Metrics` (without building a new client altogether using a host and port). This means that, if a …
> Fix high cardinality metrics tags

- syncserver/src/tokenserver/extractors.rs
Add a new `token_type` field to Tokenserver log lines to differentiate between BrowserID and OAuth requests.
Closes #1444
> feat: add token type to Tokenserver log lines

- .circleci/config.yml
and don't bother installing grpcio deps for the default build of mysql
(The switch to building separate Docker images left out version.json write)
> chore: fix the version.json in Docker builds

- Cargo.lock
- syncstorage-settings/src/lib.rs
- syncstorage-spanner/Cargo.toml
- syncstorage-spanner/src/lib.rs
- syncstorage-spanner/src/manager/deadpool.rs
- syncstorage-spanner/src/manager/session.rs
- syncstorage-spanner/src/metadata.rs
- syncstorage-spanner/src/models.rs
- syncstorage-spanner/src/pool.rs
- syncstorage-spanner/src/support.rs
and support the seemingly undocumented new leader aware routing header recently added to other spanner clients (via a setting, disabled by default)
SYNC-3922
Closes #1490
> feat: add dynamic routing headers to all Spanner ops

- syncstorage-spanner/src/BATCH_COMMIT.txt
it no longer hardcodes syncstorage configuration having moved to the rust component
> docs: remove outdated firefox-ios warning

- syncserver/src/main.rs
which produced errors when sentry ingests events
https://github.com/getsentry/sentry-rust/issues/574
[SYNC-4023](https://mozilla-hub.atlassian.net/browse/SYNC-4023)
[SYNC-4023]: https://mozilla-hub.atlassian.net/browse/SYNC-4023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: disable sentry's debug-images feature

- Cargo.lock
- syncstorage-spanner/Cargo.toml
- syncstorage-spanner/src/metadata.rs
Use suggested UA for GRPCIO header. This uses the syncserver crate version. We *may* want to use the version of `google-cloud-rust` instead?
Closes SYNC-4047
> bug: Use google specified UA for x-goog-api-client

- .cargo/audit.toml
- Cargo.lock
- Cargo.toml
- syncserver-common/src/lib.rs
- syncserver-db-common/Cargo.toml
- syncserver-settings/src/lib.rs
- syncserver/Cargo.toml
- syncserver/src/error.rs
- syncserver/src/server/mod.rs
- syncserver/src/server/test.rs
- syncserver/src/tokenserver/extractors.rs
- syncserver/src/tokenserver/handlers.rs
- syncserver/src/tokenserver/logging.rs
- syncserver/src/tokenserver/mod.rs
- syncserver/src/web/extractors.rs
- syncserver/src/web/handlers.rs
- syncserver/src/web/middleware/mod.rs
- syncserver/src/web/middleware/rejectua.rs
- syncserver/src/web/middleware/sentry.rs
- syncserver/src/web/middleware/weave.rs
- syncserver/src/web/transaction.rs
- syncstorage-db/Cargo.toml
- syncstorage-db/src/lib.rs
- syncstorage-spanner/Cargo.toml
- tokenserver-auth/Cargo.toml
- tokenserver-db/Cargo.toml
Updating dependencies:
- actix-web 4.x
- actix-http 3.x
- actix-rt 2.x
- actix-cors 0.6.x
- tokio 1.x
- reqwest 0.11.x
- deadpool 0.7.x
The unit tests are passing for me, but I'm not sure if this is ready to merge yet.  One reason I'm making a PR is that I think it will run the integration tests, which I gave up on getting to work on my machine.
I'm not sure how to land these changes.  I think some of these changes can be factored out and landed without upgrading any dependencies, I'll try to open a PR for that.  Other than that, I'm not sure if this can be split apart more.  I don't think it makes sense to upgrade any one of the dependencies without upgrading the others since that will result it duplicate crates getting compiled in (for example, the tests fail if you don't upgrade …
> Upgrading to Actix 4.x

- Cargo.lock
- syncserver/Cargo.toml
The taskcluster team was kind enough to bump `hawk` for us to resolve the duplicate dependency of `ring` (see [here](https://github.com/mozilla-services/syncstorage-rs/pull/1513#discussion_r1466812721) for context)
Additionally, I noticed a new RUSTSEC advisory so I bumped `shlex` to accommodate.
> bump: hawk, resolving duplicate dependencies and fix advisory

- .circleci/config.yml
- Dockerfile
- syncserver/src/server/test.rs
- syncstorage-spanner/src/models.rs
Looks like our Rust version was still 1.72, which is OK, but it seems like cargo-audit now depends on clap 4.5, which itself required 1.74 (see https://app.circleci.com/pipelines/github/mozilla-services/syncstorage-rs/4909/workflows/427c8cef-e69e-46f3-947f-aa9dc61b3353/jobs/18546)
**I'm keeping it as a draft till we see the tests pass**
Also, It might not be a good idea to upgrade all the way to 1.76, especially since 1.76 just got released today, so I'm open to making this 1.75 (or 1.74)
I also fixed the clippy issues that came with the upgrade
> Upgrades rustc in CI and Docker to 1.75

- syncserver/src/web/handlers.rs
- syncserver/src/web/transaction.rs
- syncstorage-db/src/lib.rs
or bodyless 412s
and kill the old periodic reporter (moved to
server::spawn_metric_periodic_reporter)
Closes SYNC-4162
> fix: don't emit a content-type header for 304s

- README.md
Simple fix, to don't display backticks on GitHub.com
Loko at the rendered file ;)
> chore(docs): add line break to do not display backticks

- Cargo.lock
- tools/tokenserver/purge_old_records.py
- tools/tokenserver/test_purge_old_records.py
don't issue deletes to their current data on syncstorage if their old "migration records" point to it
Closes SYNC-4225
> feat: special case purging of users previously migrated to Spanner

- tools/tokenserver/purge_old_records.py
- tools/tokenserver/test_purge_old_records.py
and make the comparison more clear/explicit as the goal is to check if the `fxa_kid`s match
Issue SYNC-4225
> fix: take keys_changed_at into account w/ migrated records' special case

- tools/tokenserver/database.py
- tools/tokenserver/test_process_account_events.py
Issue SYNC-4181
I pulled this out of the other closed PR @jrconlin and made a couple needed fixes/added a test
> feat: optionally force the spanner node via get_best_node

- syncserver-db-common/Cargo.toml
- syncserver-settings/src/lib.rs
- syncserver/src/server/mod.rs
- syncserver/src/web/auth.rs
- syncserver/src/web/transaction.rs
- syncstorage-db-common/src/params.rs
- syncstorage-mysql/Cargo.toml
- syncstorage-mysql/src/diesel_ext.rs
- syncstorage-mysql/src/models.rs
- syncstorage-spanner/src/manager/session.rs
- syncstorage-spanner/src/models.rs
- syncstorage-spanner/src/support.rs
- tokenserver-auth/src/crypto.rs
- tokenserver-auth/src/oauth/py.rs
- tokenserver-settings/src/lib.rs
It appears that the replacement for setting ACTIX_THREADPOOL would be to call `ServiceBuilder.worker_max_blocking_threads()` This PR introduces the ability to set this value ~either~ by using the `worker_max_blocking_threads` configuration variable ~or `ACTIX_THREADPOOL` environment variable~.
Closes #SYNC-4271
> bug: Allow threadpool size to be set.

- .circleci/config.yml
- Dockerfile
- docker-compose.e2e.mysql.yaml
- docker-compose.e2e.spanner.yaml
- docker-compose.mysql.yaml
- docker-compose.spanner.yaml
- scripts/start_mock_fxa_server.sh
- tools/spanner/Dockerfile
Bump to Debian Bookworm from Buster
* Update to Python 3.12 baseline
* Buster + Python 3.12 complicates python package installs. I've switched to using virtualenv to contain the packages we want.
* We may wish to move to Poetry or some similar system in the future. 
* Update to Rust 1.78
* This required some minor Clippy fixes.
* Added `RUST_VER` tag to easily find instances of rust versions for future updates
* Update to Cargo-Chef  
Closes: SYNC-4289
> chore: Update to debian bookworm / Python 3.12

- tokenserver-auth/src/oauth/verify.py
temporarily switch it to a "pyo3 error" so it's logged
Issue SYNC-4363
We're getting a lot of "Invalid OAuth token" errors in sentry on both stage and prod w/ 0.17.x -- I don't understand what's causing them so hopefully this helps show the underlying cause.
This should switch these errors from ["Invalid OAuth token"](https://github.com/mozilla-services/syncstorage-rs/blob/dc0d571c055741297a77dd47c70b7ef55b552530/tokenserver-auth/src/oauth/py.rs#L161) to ["pyo3 error"](https://github.com/mozilla-services/syncstorage-rs/blob/dc0d571c055741297a77dd47c70b7ef55b552530/tokenserver-auth/src/oauth/py.rs#L147), with an [accompanying Python traceback emitted to the logs](https://github.com/mozilla-services/syncstorage-rs/blob/dc0d571c055741297a77dd47c70b7ef55b552530/tokenserver-auth/src/oauth/py.rs …
> feat: debug "Invalid OAuth token" (verifier returns None) error cases

- Cargo.lock
- syncserver/src/server/mod.rs
- tokenserver-auth/src/oauth/verify.py
which its handlers (except hearbeat) return vs ApiError
otherwise we fail to take ReportableError::is_sentry_event into
account and flood sentry with all errors
and revert:
"feat: debug "Invalid OAuth token" (verifier returns None) error cases (https://github.com/mozilla-services/syncstorage-rs/pull/1595)"
This reverts commit https://github.com/mozilla-services/syncstorage-rs/commit/1443b31e5af1f10f8a52bf1bb91dc817ce0b75f2.
Issue [SYNC-4262](https://mozilla-hub.atlassian.net/browse/SYNC-4262)
[SYNC-4262]: https://mozilla-hub.atlassian.net/browse/SYNC-4262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: downcast to tokenserver's actual error type

- Dockerfile
- tools/tokenserver/process_account_events.py
and also feat: Revert "fix: revert the python3.10 match statement (for now)"
reverts the reverting from debian bookworm -> bullseye commits (minus the added RUSTSEC ignore) as they don't seem to be involved in the recent issues on prod
Issue SYNC-4363
Issue SYNC-4259
> feat: Revert "chore: revert back to bullseye (for now)"

- Cargo.lock
- syncserver-common/Cargo.toml
- syncserver-common/src/lib.rs
- syncserver-settings/src/lib.rs
also report machine parallelism @ startup
stage also shows the metrics issue, so we can verify there first
Issue SYNC-4421
> fix: ensure the pool counter's always decremented via scopeguard

- syncserver-common/src/lib.rs
- syncserver-common/src/middleware/sentry.rs
- syncserver/src/server/mod.rs
- syncserver/src/server/test.rs
- syncstorage-db/src/tests/support.rs
- syncstorage-mysql/src/test.rs
- tokenserver-db/src/models.rs
and consider idle threads as a "max" value as the underlying tokio threadpool will exit threads idle for too long
Closes SYNC-4424
> feat: track the pool's queued vs actually active tasks

- glean/metrics.yaml
- glean/pings.yaml
Addition of the metrics.yaml and pings.yaml configurations for Glean metrics. This is to measure the Daily Active User metrics internally.
Noting the open questions doc we created with Glean team [here](https://docs.google.com/document/d/1WDnn49eD0lxdcSfZzaeQZsVaKQ2KqG7VhQrP8vZDdyE/edit#heading=h.i4wnylph1d9x).  We may approach this with the following modification:
- A single event metric with the extra_keys metadata section containing the other data (platform, sync id, collection, etc)
- We may exclude the timestamp as Glean has its own internal timestamp we can use
N/A
Closes [SYNC-4415](https://mozilla-hub.atlassian.net/browse/SYNC-4415).
[SYNC-4415]: https://mozilla-hub.atlassian.net/browse/SYNC-4415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
> feat: create DAU glean schema and configs

- syncserver-db-common/src/error.rs
- syncserver/src/tokenserver/extractors.rs
- syncserver/src/tokenserver/mod.rs
- tokenserver-auth/src/lib.rs
- tokenserver-common/src/error.rs
- tokenserver-db/src/error.rs
and quiet Pool errors
Closes SYNC-4424
Note this is a quick fix, I think `TokenserverError` could use a cleaner, further overhaul: https://mozilla-hub.atlassian.net/browse/SYNC-4443
> feat: wire MysqlError's ReportableError impl into TokenserverError

- syncserver/src/server/user_agent.rs
Addition of User Agent parsing, consisting of:
Platform (Firefox Desktop, Firefox iOS, Fenix, Other)
Device family (Desktop, Mobile, Tablet, Other)
OS family (Mac, Windows, Linux, iOS, Android, other)
Note: User agent emission from iOS clients is non-standard. Two observed variants occur:
`Firefox-iOS-FxA/24` or `Firefox-iOS-Sync/115.0b32242 (iPhone; iPhone OS 17.7) (Firefox)`
See the shared spreadsheet in [SYNC-4413](https://mozilla-hub.atlassian.net/browse/SYNC-4413) for details.
As a result of Woothee being unable to parse this non-standard user agent, custom logic was added to fill in the gaps to so that the association logic can work to fill out all the matching enum values.
Subsequent PR will pull this into metarequest and apply the parsing.
Added unit tests within `user_agent` to …
> feat: user agent parsing

- Dockerfile
- tools/tokenserver/process_account_events.py
Just to be 100% on the safe side, let's go back to the old Debian bullseye until tokenserver is fully stabilized on prod.
We know this bookworm/mysql client upgrade did trigger some differences in establishing connections (they took longer to establish the max 100 we use). Tokenserver should be able to handle this difference, but let's ensure the blocking thread pool changes are successful before reattempting this bookworm/client upgrade.
It could also be useful to see the new blocking thread pool metrics before/after the bookworm upgrade, so it makes sense to revert back to the older debian/client for now.
Issue SYNC-4363
> feat: revert "feat: Revert "chore: revert back to bullseye (for now) 

- syncserver/src/web/extractors.rs
- syncstorage-db-common/src/lib.rs
- syncstorage-db/src/tests/support.rs
In looking ahead to possible opt-outs, we would want to tether to client logic using the hashed_device_id as a mechanism to delete or exclude records.
See client code : https://searchfox.org/mozilla-central/source/services/sync/modules/telemetry.sys.mjs 
This may in the end not be used, but for now it appears to be the best approach and should be included in the data review and payload of the `UserIdentifier`, passed in from the `HawkPayload`
N/A - unit testing in crates
Closes [SYNC-4448](https://mozilla-hub.atlassian.net/browse/SYNC-4448).
[SYNC-4448]: https://mozilla-hub.atlassian.net/browse/SYNC-4448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add hashed_device_id to HawkIdentifier

- glean/data-review/request.md
- glean/metrics.yaml
Per the Glean server-side collection cross-platform telemetry setup, the configuration of Glean requires a data review. This task involves the preparation of the data review document to be reviewed by a data steward. The steward, in this case, will be Travis Long , as he has been assisting us in the process of implementing the metrics for DAU using Glean. 
Subsequent filing of a bug for review will follow and a link to said data-review bug will be within the metrics.yaml file for the application.
See relevant documentation page for data review [here](https://wiki.mozilla.org/Data_Collection)
Requires data-steward review (in this case, Travis Long)
Closes [SYNC-4435](https://mozilla-hub.atlassian.net/browse/SYNC-4435).
[SYNC-4435]: …
> feat: glean metrics data review

- Cargo.lock
- Cargo.toml
includes the fix: https://github.com/getsentry/sentry-rust/pull/701
Closes SYNC-4460
> fix: upgrade sentry w/ a fix for the blocking curl Transport

- syncserver-common/src/lib.rs
I almost just caught the specific underflow case `active_threads.load(Ordering::Relaxed).min(spawned_tasks)` but I think `SeqCst` should also avoid this.
Closes SYNC-4475
> fix: avoid underflow of the queued_tasks metric

- Cargo.lock
- Cargo.toml
- syncserver-db-common/Cargo.toml
- syncstorage-spanner/Cargo.toml
- syncstorage-spanner/src/manager/deadpool.rs
- syncstorage-spanner/src/manager/mod.rs
- syncstorage-spanner/src/pool.rs
which includes a fix for its incorrect metrics:
https://github.com/bikeshedder/deadpool/issues/92
Closes SYNC-4522
> fix: upgrade to latest deadpool

- docs/adr/0001-daily-active-use-server-side-metrics-glean.md
- docs/adr/index.md
- docs/adr/template.md
Required ADR to validate approach of using Glean for server-side metrics to measure DAU.
The ADR will be created and stored in the syncstorage-rs repo and referenced in our service runbooks and documentation.
N/A
Closes [SYNC-4434](https://mozilla-hub.atlassian.net/browse/SYNC-4434).
[SYNC-4434]: https://mozilla-hub.atlassian.net/browse/SYNC-4434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: sync server side metrics adr

- Cargo.lock
- syncserver/src/web/handlers.rs
We should ideally emit the glean metrics alongside in the typical place we emit statsd metrics: after acquiring a db connection.
In the face of errors on acquiring db connections (which aren’t totally uncommon, we’re currently having spikes of them) we would emit a few less events that are likely going to be duplicates of clients later retrys anyway. The other benefit (in the case of errors) is our glean events should more closely correlate to our actual statsd metrics.
Moves everything into the `transaction_http` block, so Glean flag can still toggle.
Closes [SYNC-4548](https://mozilla-hub.atlassian.net/browse/SYNC-4548).
[SYNC-4548]: https://mozilla-hub.atlassian.net/browse/SYNC-4548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: move context of glean metrics into statsd get_collections metric

- Cargo.lock
- syncserver/src/server/mod.rs
- syncstorage-mysql/src/pool.rs
- syncstorage-settings/src/lib.rs
- syncstorage-spanner/Cargo.toml
- syncstorage-spanner/src/manager/deadpool.rs
- syncstorage-spanner/src/manager/session.rs
- syncstorage-spanner/src/pool.rs
By default, Deadpool releases unused connections pretty lazily, causing connections that may otherwise be available to be tied up unnecessarily. This could be part of what’s causing pods to run out of available connections to Spanner in certain cases. To resolve this, we should pursue a solution like the one described [here](https://github.com/bikeshedder/deadpool/issues/178#issuecomment-1036953054), where we spawn a background task that periodically releases connections that haven’t been used within a given amount of time (this amount of time should be configurable in a setting).
To do this, we’ll need to make use of the [Pool::retain](https://docs.rs/deadpool/latest/deadpool/managed/struct.Pool.html#method.retain) method, which was introduced in deadpool 0.9.3 (we’re currently on …
> Feat: add task to release unused db conns 

- .cargo/audit.toml
- Cargo.lock
- docs/tools/process_account_events.md
- docs/tools/purge_old_records_tokenserver.md
- docs/tools/spanner_purge_ttl.md
- syncserver/Cargo.toml
We should document all of our pruning scripts.
This is running: https://github.com/mozilla-services/syncstorage-rs/blob/master/tools/spanner/purge_ttl.py - Deletes expired BSOs. Runs daily.
This is running: https://github.com/mozilla-services/syncstorage-rs/blob/master/tools/tokenserver/process_account_events.py - Updates tokenserver user records per FxA events (SQS queue). Runs constantly.
This is NOT running (as of 2024-03-12): https://github.com/mozilla-services/syncstorage-rs/blob/master/tools/tokenserver/purge_old_records.py - Deletes obsolete user records (old obsolete user records, and potentially all of a user’s records if they’ve deleted their account). Currently not running at all.
N/A
Closes [SYNC-4182](https://mozilla-hub.atlassian.net/browse/SYNC-4182).
[SYNC-4182]: …
> docs: document pruning scripts

- CONTRIBUTING.md
- PULL_REQUEST_TEMPLATE.md
Update the CONTRIBUTING.md doc to emphasize commit signatures, to help prevent frustration by outside contributors.
> doc: Update CONTRIBUTING to emphasize commit signing

- .cargo/audit.toml
> **NOTE:** We can only accept PRS with all commits [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-verification). PRs that contain _any_ unsigned commits will not be accepted and the PR _must_ be resubmitted. If this is something you cannot provide, please disclose and a team member _may_ duplicate the PR as signed for you (depending on availablity and priority. Thank you for your understanding and cooperation.)
When I merged in my last pr for [adding nextest](https://github.com/mozilla-services/syncstorage-rs/pull/1651), a break from `cargo audit` snuck in, but it can't be resolved with an upgrade.
> chore: audit ignore RUSTSEC-2024-0437

- Dockerfile
as it builds on more architectures (such as arm64) and we no longer require its TLS support
derived from ghagl's and tommie's PRs (thanks!)
https://github.com/mozilla-services/syncstorage-rs/pull/1635 https://github.com/mozilla-services/syncstorage-rs/pull/1644
Closes SYNC-4690
> chore: switch back to libmariadb-dev

- Cargo.lock
- docs/tokenserver/tokenserver.md
- docs/tokenserver/tokenserver_api.md
This PR adds documentation relevant to Tokenserver, as part of addressing concerns of such information not being present during an incident.
N/A
Closes [SYNC-4183)](https://mozilla-hub.atlassian.net/browse/SYNC-4183).
> docs: add tokenserver documentation to sync

- .circleci/config.yml
- Makefile
- syncserver/src/server/test.rs
- syncserver/src/web/handlers.rs
Removed `dbg!` call and annotated some commented out calls in testing that indicate it should only be used in testing.
Added a command in the two clippy commands, in the Makefile and CI, to deny the use of `dbg!` macro calls.
See clippy docs here for [dbg_macro](https://rust-lang.github.io/rust-clippy/master/index.html#dbg_macro)
Run clippy
Closes [STOR-79](https://mozilla-hub.atlassian.net/browse/STOR-79).
[STOR-79]: https://mozilla-hub.atlassian.net/browse/STOR-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: quiet dbg calls

- syncstorage-spanner/src/batch.rs
- syncstorage-spanner/src/models.rs
- syncstorage-spanner/src/stream.rs
The one_or_none method occasionally emits errors on SQL that can only produce at most one result.
Seeing this occur from update_user_collection_quotas, get_storage_timestamp and lock_for_write_async
https://sentry.io/organizations/mozilla/issues/3517020595/?environment=prod&project=6316464&query=is%3Aunresolved
https://sentry.io/organizations/mozilla/issues/3514687669/?environment=prod&project=6316464&query=is%3Aunresolved
https://sentry.io/organizations/mozilla/issues/3516548273/?environment=prod&project=6316464&query=is%3Aunresolved
We surmise the issue here is a bug in one_or_none: it doesn’t notice its second call to next_async could potentially be an Error. It should always propagate errors from next_async before validating its result (always call next_async().transpose()?). 
This …
> bug : fix stream one or none

- tools/spanner/count_expired_rows.py
- tools/spanner/count_users.py
- tools/spanner/purge_ttl.py
- tools/spanner/test_count_expired_rows.py
- tools/spanner/test_purge_ttl.py
- tools/spanner/test_utils.py
- tools/spanner/utils.py
- tools/spanner/write_batch.py
The `SYNC_SYNCSTORAGE__DATABASE_URL` environment variable defines a spanner DSN URL that is used for parsing out the instance_id & database_id from. However, it was not parsing GCP project, which defaults to the project determined from the environment when not specified. These are defined within webservices-infra in the sync project.
This PR adds the parsing logic to pull out the project_id. Several modernizations and improvements are made to the scripts. It also adds unit tests for better maintainability. 
We’re currently working around this by specifying a GOOGLE_CLOUD_PROJECT env var, which the Spanner client recognizes, but the script should really do it itself since the project is always included in the database url setting.
Visit webservices-infra configurations and Kubernetes …
> feat: spanner scripts parse gcp project

- .circleci/config.yml
- Makefile
After adding Spanner Unit tests as a part of our CI flow, we want to report on these tests in the same way as our other Rust-based unit tests.
Create a scoped makefile command, and move the tests to run after unit tests.
Add commands to run with nexttest and output results.
CI results
Can also check `artifacts` section in CI to review test output results.
Closes [STOR-293](https://mozilla-hub.atlassian.net/browse/STOR-293).
[STOR-293]: https://mozilla-hub.atlassian.net/browse/STOR-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: collect and report spanner tests

- syncstorage-settings/src/lib.rs
Our current max_record_payload_bytes of 2mb isn’t due to any Spanner limits (which is 2.5mb for STRINGs) but is historical: it was carried over from the origin Python server-syncstorage.
(Which [was limited to 256K up until 2017](https://github.com/mozilla-services/server-syncstorage/pull/70) and was only bumped to 2MB when [Benson was writing the Go version](https://github.com/mozilla-services/go-syncstorage/pull/174))
This PR bumps:
- `max_record_payload_bytes` immediately to Spanner STRING’s limit of 2.5mb. 
- `max_post_bytes` & `max_request_bytes` also bumped accordingly
- `max_request_bytes` also needing adjustment in nginx’s config (as it also enforces it).
Closes [STOR-343](mozilla-hub.atlassian.net/browse/STOR-343).
[STOR-343]: …
> feat: bump max payload to 2.5

- .circleci/config.yml
- Dockerfile
- tools/spanner/Dockerfile
Our Python version has long been very out of date. This updates the core Python version, as well as the version for the Spanner utils. Note: Spanner Utils updated to 3.13 as we don't have the issue of maintaining mysql 8.0 which is not compatible with newer versions.
Closes [STOR-312](https://mozilla-hub.atlassian.net/browse/STOR-312).
[STOR-312]: https://mozilla-hub.atlassian.net/browse/STOR-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Chore: update sync python version 

- syncstorage-mysql/src/batch.rs
- syncstorage-mysql/src/models.rs
These methods are only called within `lock_for_write` based transactions created by `transaction_http` (all sync writes get this transaction implicitly), so there's no need for them to initiate a transaction (which actually is a savepoint since a transaction already exists). This was old sqlite impl code (possibly inherited from go-syncstorage).
This also simplifies borrowing for `&mut self`.
Issue STOR-327
> fix: kill unnecessary transactions (savepoints)

- Cargo.lock
- syncserver-db-common/src/lib.rs
- syncserver/src/tokenserver/extractors.rs
- syncserver/src/tokenserver/handlers.rs
- syncserver/src/tokenserver/mod.rs
- syncserver/src/web/handlers.rs
- syncserver/src/web/transaction.rs
- syncstorage-db-common/src/lib.rs
- syncstorage-db/src/mock.rs
- syncstorage-db/src/tests/batch.rs
- syncstorage-db/src/tests/db.rs
- syncstorage-db/src/tests/support.rs
- syncstorage-mysql/src/batch.rs
- syncstorage-mysql/src/models.rs
- syncstorage-mysql/src/test.rs
- syncstorage-spanner/src/models.rs
- tokenserver-db/src/lib.rs
- tokenserver-db/src/mock.rs
- tokenserver-db/src/models.rs
Also switches syncstorage's Db. Against https://github.com/mozilla-services/syncstorage-rs/pull/1782
Closes STOR-332
Closes STOR-327
> refactor: switch tokenserver Db methods to &mut self

- syncserver/src/server/test.rs
- syncserver/src/web/handlers.rs
- syncstorage-db-common/src/lib.rs
- syncstorage-db-common/src/params.rs
- syncstorage-db-common/src/results.rs
- syncstorage-db/src/tests/db.rs
- syncstorage-mysql/src/models.rs
- syncstorage-spanner/src/models.rs
Update the `post_bsos` db functions to return a SyncTimestamp only.  No more "success" or "failed" fields in the db results.  The http responses are unchanged.
Closes https://github.com/mozilla-services/syncstorage-rs/issues/1807
> refactor(db): return only a SyncTimestamp from post_bsos db fns
